// Code generated by abstraction-idl from abstraction-job/acceptance.thrift. DO NOT EDIT.

// abstraction.job.acceptance: declarations for index.mjs.

/** The frame transport a generated client calls: a facade binding or a connector's transport. */
interface FrameTransport {
  exchangeFrame(frame: Uint8Array): Promise<Uint8Array>;
  writeFrame(frame: Uint8Array): Promise<void>;
}

export type AcceptanceOutcome = (typeof AcceptanceOutcome)[keyof typeof AcceptanceOutcome];
export declare const AcceptanceOutcome: Readonly<{ Accepted: "accepted"; DefinitelyNotAccepted: "definitely_not_accepted"; Unknown: "unknown"; KeyConflict: "key_conflict"; Forbidden: "forbidden"; Invalid: "invalid"; Unavailable: "unavailable" }>;

// Accepted requires a receipt; other outcomes forbid one. Definite
// nonacceptance requires authoritative sealed evidence preventing any delayed
// acceptance of this identity. Absence, timeout, expired history and access
// denial are insufficient. Unavailable means a required policy decision could
// not be obtained: no admission effect and no seal were recorded, and the same
// identity may be presented again (JOB-A9).
export interface AcceptanceResult {
  outcome: AcceptanceOutcome;
  receipt: Receipt | null;
  reason: string;
}

export type CancellationOutcome = (typeof CancellationOutcome)[keyof typeof CancellationOutcome];
export declare const CancellationOutcome: Readonly<{ Requested: "requested"; AlreadyTerminal: "already_terminal"; Unknown: "unknown"; Forbidden: "forbidden"; Unsupported: "unsupported"; Unavailable: "unavailable" }>;

// Requested acknowledges cancellation intent, not stopped effects. Completion
// may win the race; observe the existing operation for its terminal result.
// Unavailable records no intent because a required policy decision could not be
// obtained; the request may be repeated.
export interface CancellationResult {
  outcome: CancellationOutcome;
}

export declare class DispatchError extends Error {
  constructor(code: string);
  code: string;
}

export type FailureCause = (typeof FailureCause)[keyof typeof FailureCause];
export declare const FailureCause: Readonly<{ Other: "other"; DigestMismatch: "digest_mismatch"; Oversize: "oversize"; ShortTransfer: "short_transfer"; Unauthorized: "unauthorized"; NotFound: "not_found"; Refused: "refused"; ServerError: "server_error"; Transport: "transport"; ResultLost: "result_lost"; Credential: "credential" }>;

export type FailureClass = (typeof FailureClass)[keyof typeof FailureClass];
export declare const FailureClass: Readonly<{ Retryable: "retryable"; Permanent: "permanent"; Unknown: "unknown" }>;

// Owner-issued acceptance epoch and minimum reconciliation retention. After
// closing an epoch the owner fences all its submissions, including delayed
// ones. This does not assert that old unknown work was never accepted. Result
// retention is the provider's declared minimum time, in milliseconds after
// completion, that complete result bytes stay readable; zero declares none
// (JOB-A11).
export interface HistoryWindow {
  logicalOwner: string;
  historyEpoch: string;
  minimumRetentionMs: bigint;
  resultRetentionMs: bigint;
}

export type InventoryOutcome = (typeof InventoryOutcome)[keyof typeof InventoryOutcome];
export declare const InventoryOutcome: Readonly<{ Page: "page"; Gap: "gap"; Forbidden: "forbidden"; Invalid: "invalid"; Unavailable: "unavailable" }>;

// Caller-scoped accepted-operation observations without paths. Only page
// carries snapshots. A noncomplete page always has a next cursor, even when no
// own operations were scanned. Complete pages have empty next. Refusals carry
// no snapshots, empty next and complete=false. Directory traversal is a weak
// live view: concurrent insertions/removals can be omitted or repeated, not a
// stable transaction snapshot. An unchanged tree is fully traversable. Large
// failure diagnostics may be replaced by a bounded generic message.
export interface InventoryPage {
  outcome: InventoryOutcome;
  snapshots: OperationSnapshot[];
  next: string;
  complete: boolean;
}

/** Bounded own-scope inventory on the acceptance provider endpoint. Authorization is independent of cursor text and uses the existing native caller scope. Listing does not authorize cross-scope Observe/Cancel or expose private provider paths. */
export declare class JobInventoryClient {
  constructor(transport: FrameTransport);
  /** List only the authenticated acceptance scope. Empty cursor starts a bounded enumeration; limit is 1..64 snapshots. Opaque cursors are bound to this provider instance and caller. Sessions expire after 30 seconds idle and restart yields gap; at most 32 sessions exist. Each call scans at most 256 directory entries and 16MiB provider bytes, with a 512KiB compact-JSON snapshot accounting budget (frame encoding overhead is additional). Empty scan pages still advance. Repeating the latest input cursor with the same limit replays its page; older cursors return gap. A lost initial empty-cursor reply can be restarted explicitly; no global scan or cross-caller authority is implied. Partial reads may return unavailable rather than falsely complete. No subscription or retention protocol is supplied. */
  listWork(cursor: string, limit: bigint): Promise<InventoryPage>;
}

export declare const JobInventoryService: Readonly<{ wireName: "abstraction.job/inventory@1"; Client: typeof JobInventoryClient }>;

/** Account-wide inventory and cross-scope cancellation on the acceptance provider endpoint, for the person acting through an operator program. A provider serves it only with a configured rights decision per call; without one every call is forbidden. A caller's own work stays on RecoverableAcceptance, OperationControl and JobInventory under ownership (JOB-A13). */
export declare class JobOperatorClient {
  constructor(transport: FrameTransport);
  /** List accepted operations of every caller scope of this provider, under the same bounds, cursor, session, replay and gap rules as JobInventory.ListWork. A cursor is bound to the caller and to this account-wide listing. Each call is decided by the rule abstraction.job/inventory.read on abstraction.job/acceptance@1 (JOB-A13); forbidden and unavailable pages carry no snapshots. Snapshots expose no provider paths and no caller scope. */
  listAccountWork(cursor: string, limit: bigint): Promise<InventoryPage>;
  /** Record cancellation intent on the operation with this receipt operation id, whichever scope accepted it. The id is 1..128 bytes of lowercase ASCII letters, digits and '-'. Each call is decided by the rule abstraction.job/acceptance.cancel on abstraction.job/acceptance@1 (JOB-A13). The intent records the caller's scope. Observe the operation through its submitter or ListAccountWork for its terminal state. */
  cancelOperation(operationId: string): Promise<OperatorCancellation>;
}

export declare const JobOperatorService: Readonly<{ wireName: "abstraction.job/operator@1"; Client: typeof JobOperatorClient }>;

export type ObservationOutcome = (typeof ObservationOutcome)[keyof typeof ObservationOutcome];
export declare const ObservationOutcome: Readonly<{ Observed: "observed"; Unknown: "unknown"; Forbidden: "forbidden"; Invalid: "invalid"; DefinitelyNotAccepted: "definitely_not_accepted"; Unavailable: "unavailable" }>;

// Exactly observed carries a snapshot; all other outcomes forbid it. Absent
// identities are unknown and observation never seals them. Definite
// nonacceptance requires an existing authoritative seal. Already accepted
// journals may be recovered. Unavailable means a required policy decision could
// not be obtained and no state was read or changed (JOB-A9).
export interface ObservationResult {
  outcome: ObservationOutcome;
  snapshot: OperationSnapshot | null;
}

/** Observation and result access use the same authenticated caller scope and request identity as RecoverableAcceptance despite their separate service wire identity. Existing acceptance methods and wire contract remain unchanged. */
export declare class OperationControlClient {
  constructor(transport: FrameTransport);
  /** Observe in the original authenticated acceptance scope. Absent identities remain unsealed; may recover an already accepted journal. */
  observeWork(identity: RequestIdentity): Promise<ObservationResult>;
  /** Read complete immutable bytes without exposing paths. Offset must be nonnegative; max_bytes must be in 1..65536. Data obeys ResultChunk bounds. Absence, failure, incomplete work and transport errors are never EOF. This read never seals an absent identity. */
  readResult(identity: RequestIdentity, offset: bigint, maxBytes: bigint): Promise<ResultRead>;
}

export declare const OperationControlService: Readonly<{ wireName: "abstraction.job/operations@1"; Client: typeof OperationControlClient }>;

// Receipt binds original request and logical owner. Cancellation requested is
// intent, not stopped effects. Progress and last-attempt failure are advisory;
// no provider paths are exposed, and the label is display text, never a path or
// a result file name. Label is the stored display label: the caller's, or one
// the kind's provider derived at acceptance, when label_derived is true. It is
// absent when neither exists (JOB-A12). Waiting is the word the kind's provider
// reports for accepted, unfinished work held by a condition the submission set,
// such as network:metered; empty when nothing holds it. It is advisory and
// never a failure (JOB-A15).
export interface OperationSnapshot {
  receipt: Receipt;
  state: WorkState;
  progress: WorkProgress;
  cancellationRequested: boolean;
  failure: WorkFailure | null;
  label: string;
  labelDerived: boolean;
  waiting: string;
}

// Requested acknowledges cancellation intent recorded on the named operation,
// whichever scope accepted it; it is not stopped effects. Already_terminal
// names an operation that ended. Unknown names no operation of this provider.
// Invalid is a malformed operation id. Forbidden is an evaluated refusal of the
// caller's rule. Unavailable records no intent because the decision or the
// store could not be reached (JOB-A13).
export interface OperatorCancellation {
  outcome: OperatorCancellationOutcome;
}

export type OperatorCancellationOutcome = (typeof OperatorCancellationOutcome)[keyof typeof OperatorCancellationOutcome];
export declare const OperatorCancellationOutcome: Readonly<{ Requested: "requested"; AlreadyTerminal: "already_terminal"; Unknown: "unknown"; Forbidden: "forbidden"; Invalid: "invalid"; Unavailable: "unavailable" }>;

// Recoverable acceptance evidence. Retention is a minimum duration from
// original acceptance, never renewed by replay. Expiry does not end work,
// transfer ownership or authorize duplicate execution. IDs confer no authority.
export interface Receipt {
  identity: RequestIdentity;
  logicalOwner: string;
  operationId: string;
  acceptedGuarantees: string[];
  historyRetentionMs: bigint;
}

/** Version 1 recoverable acceptance vocabulary, local or remote. Providers must implement atomic recovery and downstream deduplication before advertising those guarantees. Legacy Store is not implicitly upgraded. */
export declare class RecoverableAcceptanceClient {
  constructor(transport: FrameTransport);
  /** Obtain the logical owner and history epoch before first submission; creates no work. */
  getHistoryWindow(): Promise<HistoryWindow>;
  /** Atomically associate authenticated request identity, arguments, operation and guarantees before acknowledging. Duplicate equal arguments recover the original receipt. No weaker provider fallback on unknown. */
  submit(submission: Submission): Promise<AcceptanceResult>;
  /** Authorized lookup at the original logical owner after lost request, lost reply or caller restart. A definite negative seals the identity against delayed submissions. Unavailable evidence gives unknown. */
  reconcile(identity: RequestIdentity): Promise<AcceptanceResult>;
  /** Authorized explicit work cancellation. Cancelling a transport wait is never this operation and never relinquishes accepted work ownership. */
  cancelWork(identity: RequestIdentity): Promise<CancellationResult>;
}

export declare const RecoverableAcceptanceService: Readonly<{ wireName: "abstraction.job/acceptance@1"; Client: typeof RecoverableAcceptanceClient }>;

export declare class Refusal extends Error {
  constructor(word: string, offset: number);
  word: "malformed" | "bad_string" | "number_spelling" | "wrong_type" | "depth_exceeded" | "duplicate_key" | "duplicate_field" | "unknown_field" | "missing_field" | "bad_binary" | "bad_enum" | "trailing_bytes";
  offset: number;
}

// Stable SDK key in an owner-issued history epoch. Scope is authenticated
// caller plus this service contract, never a caller-provided principal. Persist
// before send for restart recovery. Attempt is a nonnegative explicit retry
// number for the same key and epoch; zero is the original request. Attempt N+1
// is eligible only after attempt N failed terminally or was sealed (JOB-A7).
export interface RequestIdentity {
  key: string;
  historyEpoch: string;
  attempt: bigint;
}

// Complete immutable result bytes bound to the original receipt. Offset equals
// requested nonnegative offset and is at most nonnegative total. Data length is
// at most requested max_bytes and total-offset. EOF is true exactly when offset
// plus data length equals total, including an empty complete result. Data is
// nonempty unless offset equals total and EOF is true. Missing data and errors
// never imply EOF.
export interface ResultChunk {
  receipt: Receipt;
  offset: bigint;
  total: bigint;
  data: Uint8Array;
  eof: boolean;
}

export type ResultOutcome = (typeof ResultOutcome)[keyof typeof ResultOutcome];
export declare const ResultOutcome: Readonly<{ Data: "data"; NotReady: "not_ready"; Unavailable: "unavailable"; Unsupported: "unsupported"; Unknown: "unknown"; Forbidden: "forbidden"; Invalid: "invalid" }>;

// Exactly data carries a chunk; other outcomes forbid it. Only complete
// immutable results produce data. Incomplete work is not_ready; missing
// completed bytes are unavailable. Unsupported access, unknown identity,
// forbidden access and invalid bounds remain distinct.
export interface ResultRead {
  outcome: ResultOutcome;
  chunk: ResultChunk | null;
}

export declare class ServiceError extends Error {
  constructor(code: string, message?: string);
  code: string;
}

export type ServiceErrorCode = (typeof ServiceErrorCode)[keyof typeof ServiceErrorCode];
export declare const ServiceErrorCode: Readonly<{ HandlerError: "handler_error"; InvalidResult: "invalid_result"; UnknownVersion: "unknown_version"; UnknownService: "unknown_service"; UnknownMethod: "unknown_method"; WrongMode: "wrong_mode"; Forbidden: "forbidden" }>;

// Opaque kind-specific specification bytes, not a second tagged job Record.
// Equality includes kind, exact spec bytes and the set of required guarantees.
// Credentials are supplied at the authorized service boundary. Label is the
// caller's display text for the operation, 1 to 256 UTF-8 bytes after trimming
// on one line; an empty label is absent, and an invalid one makes Submit
// invalid. It is outside equality and fixed at acceptance (JOB-A12).
export interface Submission {
  identity: RequestIdentity;
  kind: string;
  spec: Uint8Array;
  requiredGuarantees: string[];
  label: string;
}

// Last-attempt failure. Unknown classification remains unknown; do not infer it
// from message text. Retryable failure can coexist with pending work. Permanent
// classification means the provider will not try this operation again and its
// state is failed. Cause is the provider's typed reason when known; empty means
// unreported, and an unrecognized cause is treated as other.
export interface WorkFailure {
  classification: FailureClass;
  message: string;
  cause: FailureCause | (string & {});
}

// Advisory nonnegative progress. Zero total means unknown. Progress does not
// authorize delivery or imply completion.
export interface WorkProgress {
  done: bigint;
  total: bigint;
}

export type WorkState = (typeof WorkState)[keyof typeof WorkState];
export declare const WorkState: Readonly<{ Pending: "pending"; Running: "running"; Transferred: "transferred"; Complete: "complete"; Failed: "failed"; Cancelled: "cancelled" }>;

export declare const acceptanceErrorCodes: readonly ["forbidden"];

export declare const admissionGuarantees: readonly ["abstraction.job/caller-exit@1", "abstraction.job/service-restart@1", "abstraction.job/reconciliation@1"];

export declare function decode(data: Uint8Array): AcceptanceResult;

export declare function encode(v: AcceptanceResult): Uint8Array;

export declare function newAcceptanceResult(): AcceptanceResult;

export declare function newCancellationResult(): CancellationResult;

export declare function newHistoryWindow(): HistoryWindow;

export declare function newInventoryPage(): InventoryPage;

export declare function newObservationResult(): ObservationResult;

export declare function newOperationSnapshot(): OperationSnapshot;

export declare function newOperatorCancellation(): OperatorCancellation;

export declare function newReceipt(): Receipt;

export declare function newRequestIdentity(): RequestIdentity;

export declare function newResultChunk(): ResultChunk;

export declare function newResultRead(): ResultRead;

export declare function newSubmission(): Submission;

export declare function newWorkFailure(): WorkFailure;

export declare function newWorkProgress(): WorkProgress;

export declare const resourceActions: readonly ["abstraction.job/acceptance.submit", "abstraction.job/acceptance.cancel", "abstraction.job/inventory.read"];

export {};
