// Code generated by abstraction-idl from abstraction-job/acceptance.thrift. DO NOT EDIT.

const HEX = "0123456789abcdef";
const ENC = new TextEncoder();
const SHORT = { 0x22: '\\"', 0x5c: "\\\\", 0x08: "\\b", 0x0c: "\\f", 0x0a: "\\n", 0x0d: "\\r", 0x09: "\\t" };

class Out {
  constructor() { this.b = []; }
  byte(c) { this.b.push(c); }
  ascii(s) { for (let i = 0; i < s.length; i++) this.b.push(s.charCodeAt(i)); }
  bytes() { return Uint8Array.from(this.b); }
}

function escByte(out, c) {
  const short = SHORT[c];
  if (short !== undefined) out.ascii(short);
  else if (c < 0x20) out.ascii("\\u00" + HEX[c >> 4] + HEX[c & 0xf]);
  else out.byte(c);
}

// Every integer the definition calls i64 is a BigInt here, because Number
// rounds above 2^53 and two values in the conformance record are i64 extremes.
function num(out, n) { out.ascii(BigInt(n).toString()); }

function pad(out, depth) { for (let i = 0; i < depth * 2; i++) out.byte(0x20); }

function strs(out, v, depth) {
  if (v.length === 0) { out.ascii("[]"); return; }
  out.ascii("[\n");
  for (let i = 0; i < v.length; i++) {
    pad(out, depth + 1);
    esc(out, v[i]);
    if (i + 1 < v.length) out.byte(0x2c);
    out.byte(0x0a);
  }
  pad(out, depth);
  out.byte(0x5d);
}

const isWs = (c) => c === 0x20 || c === 0x09 || c === 0x0a || c === 0x0d;

function raw(out, s, depth) {
  const b = typeof s === "string" ? ENC.encode(s) : s;
  let i = 0;
  while (i < b.length) {
    const c = b[i];
    if (isWs(c)) { i++; continue; }
    if (c === 0x22) {
      let j = i + 1;
      while (j < b.length) {
        if (b[j] === 0x5c) { j += 2; continue; }
        if (b[j] === 0x22) { j++; break; }
        j++;
      }
      for (let k = i; k < j; k++) out.byte(b[k]);
      i = j;
    } else if (c === 0x7b || c === 0x5b) {
      out.byte(c);
      i++;
      let j = i;
      while (j < b.length && isWs(b[j])) j++;
      if (j < b.length && (b[j] === 0x7d || b[j] === 0x5d)) { out.byte(b[j]); i = j + 1; }
      else { depth++; out.byte(0x0a); pad(out, depth); }
    } else if (c === 0x7d || c === 0x5d) {
      depth--;
      out.byte(0x0a);
      pad(out, depth);
      out.byte(c);
      i++;
    } else if (c === 0x2c) {
      out.ascii(",\n");
      pad(out, depth);
      i++;
    } else if (c === 0x3a) {
      out.ascii(": ");
      i++;
    } else {
      out.byte(c);
      i++;
    }
  }
}

// A JavaScript string sorts by UTF-16 code unit, which puts U+1D11E before
// U+FFFD where every other target puts it after. The definition declares UTF-8
// byte order, so the comparison is done on the encoded bytes.
function byteLess(a, b) {
  const x = ENC.encode(a), y = ENC.encode(b);
  const n = Math.min(x.length, y.length);
  for (let i = 0; i < n; i++) if (x[i] !== y[i]) return x[i] - y[i];
  return x.length - y.length;
}

function rawmap(out, m, depth) {
  const keys = Object.keys(m).sort(byteLess);
  if (keys.length === 0) { out.ascii("{}"); return; }
  out.ascii("{\n");
  for (let i = 0; i < keys.length; i++) {
    pad(out, depth + 1);
    esc(out, keys[i]);
    out.ascii(": ");
    raw(out, m[keys[i]], depth + 1);
    if (i + 1 < keys.length) out.byte(0x2c);
    out.byte(0x0a);
  }
  pad(out, depth);
  out.byte(0x7d);
}

function esc(out, s) {
  out.byte(0x22);
  for (const c of ENC.encode(s)) escByte(out, c);
  out.byte(0x22);
}

function binaryPresent(value) {
  if (!(value instanceof Uint8Array)) throw new Refusal("wrong_type", 0);
  return value.length !== 0;
}
function encodeBinary(value) {
  binaryPresent(value);
  const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
  const out = [];
  for (let i = 0; i < value.length; i += 3) {
    const left = value.length - i;
    const v = (value[i] << 16) | ((left > 1 ? value[i+1] : 0) << 8) | (left > 2 ? value[i+2] : 0);
    out.push(alphabet[(v >>> 18) & 63], alphabet[(v >>> 12) & 63], left > 1 ? alphabet[(v >>> 6) & 63] : "=", left > 2 ? alphabet[v & 63] : "=");
  }
  return out.join("");
}
function readBinary(r) {
  const text = r.string();
  const bad = () => { throw r.refuse("bad_binary"); };
  if (text.length % 4 !== 0) bad();
  const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
  const out = new Uint8Array(text.length / 4 * 3);
  let size = 0;
  for (let i = 0; i < text.length; i += 4) {
    let v = 0, pad = 0;
    for (let j = 0; j < 4; j++) {
      const c = text[i+j]; let digit = 0;
      if (c === "=") { if (j < 2 || i+4 !== text.length) bad(); pad++; }
      else { if (pad !== 0) bad(); digit = alphabet.indexOf(c); if (digit < 0) bad(); }
      v = (v << 6) | digit;
    }
    out[size++] = (v >>> 16) & 255;
    if (pad < 2) out[size++] = (v >>> 8) & 255;
    if (pad < 1) out[size++] = v & 255;
  }
  const result = out.slice(0, size);
  if (encodeBinary(result) !== text) bad();
  return result;
}

function writeList(out, v, depth, enc) {
  if (v.length === 0) { out.ascii("[]"); return; }
  out.ascii("[\n");
  for (let i = 0; i < v.length; i++) {
    pad(out, depth + 1);
    enc(out, v[i], depth + 1);
    if (i + 1 < v.length) out.byte(0x2c);
    out.byte(0x0a);
  }
  pad(out, depth);
  out.byte(0x5d);
}

export const AcceptanceOutcome = Object.freeze({
  Accepted: "accepted",
  DefinitelyNotAccepted: "definitely_not_accepted",
  Unknown: "unknown",
  KeyConflict: "key_conflict",
  Forbidden: "forbidden",
  Invalid: "invalid",
  Unavailable: "unavailable",
});

export const CancellationOutcome = Object.freeze({
  Requested: "requested",
  AlreadyTerminal: "already_terminal",
  Unknown: "unknown",
  Forbidden: "forbidden",
  Unsupported: "unsupported",
  Unavailable: "unavailable",
});

export const WorkState = Object.freeze({
  Pending: "pending",
  Running: "running",
  Transferred: "transferred",
  Complete: "complete",
  Failed: "failed",
  Cancelled: "cancelled",
});

export const FailureClass = Object.freeze({
  Retryable: "retryable",
  Permanent: "permanent",
  Unknown: "unknown",
});

export const FailureCause = Object.freeze({
  Other: "other",
  DigestMismatch: "digest_mismatch",
  Oversize: "oversize",
  ShortTransfer: "short_transfer",
  Unauthorized: "unauthorized",
  NotFound: "not_found",
  Refused: "refused",
  ServerError: "server_error",
  Transport: "transport",
  ResultLost: "result_lost",
  Credential: "credential",
});

export const ObservationOutcome = Object.freeze({
  Observed: "observed",
  Unknown: "unknown",
  Forbidden: "forbidden",
  Invalid: "invalid",
  DefinitelyNotAccepted: "definitely_not_accepted",
  Unavailable: "unavailable",
});

export const ResultOutcome = Object.freeze({
  Data: "data",
  NotReady: "not_ready",
  Unavailable: "unavailable",
  Unsupported: "unsupported",
  Unknown: "unknown",
  Forbidden: "forbidden",
  Invalid: "invalid",
});

export const InventoryOutcome = Object.freeze({
  Page: "page",
  Gap: "gap",
  Forbidden: "forbidden",
  Invalid: "invalid",
  Unavailable: "unavailable",
});

export const OperatorCancellationOutcome = Object.freeze({
  Requested: "requested",
  AlreadyTerminal: "already_terminal",
  Unknown: "unknown",
  Forbidden: "forbidden",
  Invalid: "invalid",
  Unavailable: "unavailable",
});

export const ServiceErrorCode = Object.freeze({
  HandlerError: "handler_error",
  InvalidResult: "invalid_result",
  UnknownVersion: "unknown_version",
  UnknownService: "unknown_service",
  UnknownMethod: "unknown_method",
  WrongMode: "wrong_mode",
  Forbidden: "forbidden",
});

export const admissionGuarantees = ["abstraction.job/caller-exit@1", "abstraction.job/service-restart@1", "abstraction.job/reconciliation@1"];

export const acceptanceErrorCodes = ["forbidden"];

export const resourceActions = ["abstraction.job/acceptance.submit", "abstraction.job/acceptance.cancel", "abstraction.job/inventory.read"];

function writeRequestIdentity(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "key");
  out.ascii(": ");
  esc(out, v.key);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "history_epoch");
  out.ascii(": ");
  esc(out, v.historyEpoch);
  if (v.attempt !== 0n) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "attempt");
    out.ascii(": ");
    num(out, v.attempt);
  }
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeSubmission(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "identity");
  out.ascii(": ");
  writeRequestIdentity(out, v.identity, depth + 1);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "kind");
  out.ascii(": ");
  esc(out, v.kind);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "spec");
  out.ascii(": ");
  esc(out, encodeBinary(v.spec));
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "required_guarantees");
  out.ascii(": ");
  strs(out, v.requiredGuarantees, depth + 1);
  if (v.label !== "") {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "label");
    out.ascii(": ");
    esc(out, v.label);
  }
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeReceipt(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "identity");
  out.ascii(": ");
  writeRequestIdentity(out, v.identity, depth + 1);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "logical_owner");
  out.ascii(": ");
  esc(out, v.logicalOwner);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "operation_id");
  out.ascii(": ");
  esc(out, v.operationId);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "accepted_guarantees");
  out.ascii(": ");
  strs(out, v.acceptedGuarantees, depth + 1);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "history_retention_ms");
  out.ascii(": ");
  num(out, v.historyRetentionMs);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeAcceptanceResult(out, v, depth) {
    if (typeof v.outcome !== "string") throw new Refusal("wrong_type",0);
    if (v.outcome !== "accepted" && v.outcome !== "definitely_not_accepted" && v.outcome !== "unknown" && v.outcome !== "key_conflict" && v.outcome !== "forbidden" && v.outcome !== "invalid" && v.outcome !== "unavailable") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "outcome");
  out.ascii(": ");
  esc(out, v.outcome);
  if (v.receipt !== undefined && v.receipt !== null) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "receipt");
    out.ascii(": ");
    writeReceipt(out, v.receipt, depth + 1);
  }
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "reason");
  out.ascii(": ");
  esc(out, v.reason);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeHistoryWindow(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "logical_owner");
  out.ascii(": ");
  esc(out, v.logicalOwner);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "history_epoch");
  out.ascii(": ");
  esc(out, v.historyEpoch);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "minimum_retention_ms");
  out.ascii(": ");
  num(out, v.minimumRetentionMs);
  if (v.resultRetentionMs !== 0n) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "result_retention_ms");
    out.ascii(": ");
    num(out, v.resultRetentionMs);
  }
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeCancellationResult(out, v, depth) {
    if (typeof v.outcome !== "string") throw new Refusal("wrong_type",0);
    if (v.outcome !== "requested" && v.outcome !== "already_terminal" && v.outcome !== "unknown" && v.outcome !== "forbidden" && v.outcome !== "unsupported" && v.outcome !== "unavailable") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "outcome");
  out.ascii(": ");
  esc(out, v.outcome);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeWorkProgress(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "done");
  out.ascii(": ");
  num(out, v.done);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "total");
  out.ascii(": ");
  num(out, v.total);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeWorkFailure(out, v, depth) {
    if (typeof v.classification !== "string") throw new Refusal("wrong_type",0);
    if (v.classification !== "retryable" && v.classification !== "permanent" && v.classification !== "unknown") { throw new Refusal("bad_enum",0); }
    if (v.cause !== "") {
    if (typeof v.cause !== "string") throw new Refusal("wrong_type",0);
    }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "classification");
  out.ascii(": ");
  esc(out, v.classification);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "message");
  out.ascii(": ");
  esc(out, v.message);
  if (v.cause !== "") {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "cause");
    out.ascii(": ");
    esc(out, v.cause);
  }
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOperationSnapshot(out, v, depth) {
    if (typeof v.state !== "string") throw new Refusal("wrong_type",0);
    if (v.state !== "pending" && v.state !== "running" && v.state !== "transferred" && v.state !== "complete" && v.state !== "failed" && v.state !== "cancelled") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "receipt");
  out.ascii(": ");
  writeReceipt(out, v.receipt, depth + 1);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "state");
  out.ascii(": ");
  esc(out, v.state);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "progress");
  out.ascii(": ");
  writeWorkProgress(out, v.progress, depth + 1);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "cancellation_requested");
  out.ascii(": ");
  out.ascii(v.cancellationRequested ? "true" : "false");
  if (v.failure !== undefined && v.failure !== null) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "failure");
    out.ascii(": ");
    writeWorkFailure(out, v.failure, depth + 1);
  }
  if (v.label !== "") {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "label");
    out.ascii(": ");
    esc(out, v.label);
  }
  if (v.labelDerived) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "label_derived");
    out.ascii(": ");
    out.ascii(v.labelDerived ? "true" : "false");
  }
  if (v.waiting !== "") {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "waiting");
    out.ascii(": ");
    esc(out, v.waiting);
  }
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeObservationResult(out, v, depth) {
    if (typeof v.outcome !== "string") throw new Refusal("wrong_type",0);
    if (v.outcome !== "observed" && v.outcome !== "unknown" && v.outcome !== "forbidden" && v.outcome !== "invalid" && v.outcome !== "definitely_not_accepted" && v.outcome !== "unavailable") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "outcome");
  out.ascii(": ");
  esc(out, v.outcome);
  if (v.snapshot !== undefined && v.snapshot !== null) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "snapshot");
    out.ascii(": ");
    writeOperationSnapshot(out, v.snapshot, depth + 1);
  }
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeResultChunk(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "receipt");
  out.ascii(": ");
  writeReceipt(out, v.receipt, depth + 1);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "offset");
  out.ascii(": ");
  num(out, v.offset);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "total");
  out.ascii(": ");
  num(out, v.total);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "data");
  out.ascii(": ");
  esc(out, encodeBinary(v.data));
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "eof");
  out.ascii(": ");
  out.ascii(v.eof ? "true" : "false");
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeResultRead(out, v, depth) {
    if (typeof v.outcome !== "string") throw new Refusal("wrong_type",0);
    if (v.outcome !== "data" && v.outcome !== "not_ready" && v.outcome !== "unavailable" && v.outcome !== "unsupported" && v.outcome !== "unknown" && v.outcome !== "forbidden" && v.outcome !== "invalid") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "outcome");
  out.ascii(": ");
  esc(out, v.outcome);
  if (v.chunk !== undefined && v.chunk !== null) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "chunk");
    out.ascii(": ");
    writeResultChunk(out, v.chunk, depth + 1);
  }
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeInventoryPage(out, v, depth) {
    if (typeof v.outcome !== "string") throw new Refusal("wrong_type",0);
    if (v.outcome !== "page" && v.outcome !== "gap" && v.outcome !== "forbidden" && v.outcome !== "invalid" && v.outcome !== "unavailable") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "outcome");
  out.ascii(": ");
  esc(out, v.outcome);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "snapshots");
  out.ascii(": ");
  writeList(out, v.snapshots, depth + 1, writeOperationSnapshot);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "next");
  out.ascii(": ");
  esc(out, v.next);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "complete");
  out.ascii(": ");
  out.ascii(v.complete ? "true" : "false");
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOperatorCancellation(out, v, depth) {
    if (typeof v.outcome !== "string") throw new Refusal("wrong_type",0);
    if (v.outcome !== "requested" && v.outcome !== "already_terminal" && v.outcome !== "unknown" && v.outcome !== "forbidden" && v.outcome !== "invalid" && v.outcome !== "unavailable") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "outcome");
  out.ascii(": ");
  esc(out, v.outcome);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOARecoverableAcceptanceGetHistoryWindowArguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x7d);
}

function writeOARecoverableAcceptanceSubmitArguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "submission");
  out.ascii(": ");
  writeSubmission(out, v.submission, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOARecoverableAcceptanceReconcileArguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "identity");
  out.ascii(": ");
  writeRequestIdentity(out, v.identity, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOARecoverableAcceptanceCancelWorkArguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "identity");
  out.ascii(": ");
  writeRequestIdentity(out, v.identity, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAOperationControlObserveWorkArguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "identity");
  out.ascii(": ");
  writeRequestIdentity(out, v.identity, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAOperationControlReadResultArguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "identity");
  out.ascii(": ");
  writeRequestIdentity(out, v.identity, depth + 1);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "offset");
  out.ascii(": ");
  num(out, v.offset);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "max_bytes");
  out.ascii(": ");
  num(out, v.maxBytes);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAJobInventoryListWorkArguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "cursor");
  out.ascii(": ");
  esc(out, v.cursor);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "limit");
  out.ascii(": ");
  num(out, v.limit);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAJobOperatorListAccountWorkArguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "cursor");
  out.ascii(": ");
  esc(out, v.cursor);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "limit");
  out.ascii(": ");
  num(out, v.limit);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAJobOperatorCancelOperationArguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "operation_id");
  out.ascii(": ");
  esc(out, v.operationId);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAServiceFrame(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "version");
  out.ascii(": ");
  num(out, v.version);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "service");
  out.ascii(": ");
  esc(out, v.service);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "method");
  out.ascii(": ");
  esc(out, v.method);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "arguments");
  out.ascii(": ");
  for (const byte of (typeof v.arguments === "string" ? ENC.encode(v.arguments) : v.arguments)) out.byte(byte);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAServiceReply(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "version");
  out.ascii(": ");
  num(out, v.version);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "service");
  out.ascii(": ");
  esc(out, v.service);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "method");
  out.ascii(": ");
  esc(out, v.method);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "ok");
  out.ascii(": ");
  out.ascii(v.ok ? "true" : "false");
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "payload");
  out.ascii(": ");
  for (const byte of (typeof v.payload === "string" ? ENC.encode(v.payload) : v.payload)) out.byte(byte);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAServiceError(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "code");
  out.ascii(": ");
  esc(out, v.code);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "message");
  out.ascii(": ");
  esc(out, v.message);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOARecoverableAcceptanceGetHistoryWindowResult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  writeHistoryWindow(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOARecoverableAcceptanceSubmitResult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  writeAcceptanceResult(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOARecoverableAcceptanceReconcileResult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  writeAcceptanceResult(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOARecoverableAcceptanceCancelWorkResult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  writeCancellationResult(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAOperationControlObserveWorkResult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  writeObservationResult(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAOperationControlReadResultResult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  writeResultRead(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAJobInventoryListWorkResult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  writeInventoryPage(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAJobOperatorListAccountWorkResult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  writeInventoryPage(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAJobOperatorCancelOperationResult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  writeOperatorCancellation(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function encode(v) {
  const out = new Out();
  writeAcceptanceResult(out, v, 0);
  out.byte(0x0a);
  return out.bytes();
}

// A BOM inside a JSON string is data, not a stream signature.
const DEC = new TextDecoder("utf-8", {ignoreBOM: true});
const DEPTH_LIMIT = 64;
const I64_DIGITS = 19;
const UNESCAPE = { 0x22: 0x22, 0x5c: 0x5c, 0x2f: 0x2f, 0x62: 0x08, 0x66: 0x0c, 0x6e: 0x0a, 0x72: 0x0d, 0x74: 0x09 };

export class Refusal extends Error {
  constructor(word, offset) {
    super("refused: " + word + " at byte " + offset);
    this.name = "Refusal";
    this.word = word;
    this.offset = offset;
  }
}

function appendRune(out, cp) {
  if (cp < 0x80) out.push(cp);
  else if (cp < 0x800) out.push(0xc0 | (cp >> 6), 0x80 | (cp & 0x3f));
  else if (cp < 0x10000) out.push(0xe0 | (cp >> 12), 0x80 | ((cp >> 6) & 0x3f), 0x80 | (cp & 0x3f));
  else out.push(0xf0 | (cp >> 18), 0x80 | ((cp >> 12) & 0x3f), 0x80 | ((cp >> 6) & 0x3f), 0x80 | (cp & 0x3f));
}

// TextDecoder substitutes U+FFFD for a bad sequence rather than reporting it, so
// the bytes are checked before they are decoded and the refusal says so.
function validUtf8(b) {
  for (let i = 0; i < b.length; ) {
    const c = b[i];
    if (c < 0x80) { i++; continue; }
    let n, cp;
    if (c >> 5 === 0x6) { n = 2; cp = c & 0x1f; }
    else if (c >> 4 === 0xe) { n = 3; cp = c & 0x0f; }
    else if (c >> 3 === 0x1e) { n = 4; cp = c & 0x07; }
    else return false;
    if (i + n > b.length) return false;
    for (let k = 1; k < n; k++) {
      if (b[i + k] >> 6 !== 0x2) return false;
      cp = (cp << 6) | (b[i + k] & 0x3f);
    }
    const lowest = [0, 0, 0x80, 0x800, 0x10000][n];
    if (cp < lowest || cp > 0x10ffff || (cp >= 0xd800 && cp <= 0xdfff)) return false;
    i += n;
  }
  return true;
}

class Reader {
  constructor(buf) { this.buf = buf; this.pos = 0; this.depth = 0; }

  refuse(word) { return new Refusal(word, this.pos); }

  at() { return this.pos < this.buf.length ? this.buf[this.pos] : 0; }

  digit() { const c = this.at(); return c >= 0x30 && c <= 0x39; }

  ws() { while (this.pos < this.buf.length && isWs(this.buf[this.pos])) this.pos++; }

  enter() {
    this.depth++;
    if (this.depth > DEPTH_LIMIT) throw this.refuse("depth_exceeded");
  }

  string() {
    if (this.at() !== 0x22) throw this.refuse("wrong_type");
    this.pos++;
    const out = [];
    for (;;) {
      if (this.pos >= this.buf.length) throw this.refuse("malformed");
      const c = this.buf[this.pos];
      if (c === 0x22) {
        this.pos++;
        const bytes = Uint8Array.from(out);
        if (!validUtf8(bytes)) throw this.refuse("bad_string");
        return DEC.decode(bytes);
      }
      if (c < 0x20) throw this.refuse("bad_string");
      if (c === 0x5c) this.escape(out);
      else { out.push(c); this.pos++; }
    }
  }

  escape(out) {
    this.pos++;
    if (this.pos >= this.buf.length) throw this.refuse("malformed");
    const c = this.buf[this.pos];
    this.pos++;
    const plain = UNESCAPE[c];
    if (plain !== undefined) { out.push(plain); return; }
    if (c !== 0x75) throw this.refuse("bad_string");
    let u = this.hex4();
    if (u >= 0xdc00 && u <= 0xdfff) throw this.refuse("bad_string");
    if (u >= 0xd800 && u <= 0xdbff) {
      if (this.pos + 1 >= this.buf.length || this.buf[this.pos] !== 0x5c || this.buf[this.pos + 1] !== 0x75)
        throw this.refuse("bad_string");
      this.pos += 2;
      const low = this.hex4();
      if (low < 0xdc00 || low > 0xdfff) throw this.refuse("bad_string");
      u = 0x10000 + ((u - 0xd800) << 10) + (low - 0xdc00);
    }
    appendRune(out, u);
  }

  hex4() {
    if (this.pos + 4 > this.buf.length) throw this.refuse("bad_string");
    let u = 0;
    for (let i = 0; i < 4; i++) {
      const c = this.buf[this.pos + i];
      if (c >= 0x30 && c <= 0x39) u = (u << 4) | (c - 0x30);
      else if (c >= 0x61 && c <= 0x66) u = (u << 4) | (c - 0x61 + 10);
      else if (c >= 0x41 && c <= 0x46) u = (u << 4) | (c - 0x41 + 10);
      else throw this.refuse("bad_string");
    }
    this.pos += 4;
    return u;
  }

  integer(low, high) {
    const c = this.at();
    if (c !== 0x2d && (c < 0x30 || c > 0x39)) throw this.refuse("wrong_type");
    const negative = c === 0x2d;
    if (negative) this.pos++;
    if (!this.digit()) throw this.refuse("malformed");
    const start = this.pos;
    if (this.at() === 0x30) this.pos++;
    else while (this.digit()) this.pos++;
    const after = this.at();
    if (after === 0x2e || after === 0x65 || after === 0x45 || this.digit()) throw this.refuse("number_spelling");
    if (this.pos - start > I64_DIGITS) throw this.refuse("number_spelling");
    let n = BigInt(String.fromCharCode(...this.buf.subarray(start, this.pos)));
    if (negative) {
      if (n === 0n) throw this.refuse("number_spelling");
      n = -n;
    }
    if (n < low || n > high) throw this.refuse("number_spelling");
    return n;
  }

  boolean() {
    if (this.at() === 0x74) { this.literal("true"); return true; }
    if (this.at() === 0x66) { this.literal("false"); return false; }
    throw this.refuse("wrong_type");
  }

  literal(word) {
    for (let i = 0; i < word.length; i++)
      if (this.buf[this.pos + i] !== word.charCodeAt(i)) throw this.refuse("malformed");
    this.pos += word.length;
  }

  strList() {
    if (this.at() !== 0x5b) throw this.refuse("wrong_type");
    this.enter();
    this.pos++;
    const out = [];
    this.ws();
    if (this.at() !== 0x5d) {
      for (;;) {
        this.ws();
        out.push(this.string());
        this.ws();
        if (this.at() !== 0x2c) break;
        this.pos++;
      }
    }
    if (this.at() !== 0x5d) throw this.refuse("malformed");
    this.pos++;
    this.depth--;
    return out;
  }

  rawMap() {
    if (this.at() !== 0x7b) throw this.refuse("wrong_type");
    this.enter();
    this.pos++;
    const out = Object.create(null);
    this.ws();
    if (this.at() !== 0x7d) {
      for (;;) {
        this.ws();
        if (this.at() !== 0x22) throw this.refuse("malformed");
        const k = this.string();
        if (k in out) throw this.refuse("duplicate_key");
        this.ws();
        if (this.at() !== 0x3a) throw this.refuse("malformed");
        this.pos++;
        this.ws();
        out[k] = this.rawValue();
        this.ws();
        if (this.at() !== 0x2c) break;
        this.pos++;
      }
    }
    if (this.at() !== 0x7d) throw this.refuse("malformed");
    this.pos++;
    this.depth--;
    return out;
  }

  rawValue() {
    const start = this.pos;
    this.skipValue();
    return this.buf.subarray(start, this.pos);
  }

  skipValue() {
    const c = this.at();
    if (c === 0x22) this.skipString();
    else if (c === 0x7b || c === 0x5b) this.skipContainer();
    else if (c === 0x74) this.literal("true");
    else if (c === 0x66) this.literal("false");
    else if (c === 0x6e) this.literal("null");
    else if (c === 0x2d || (c >= 0x30 && c <= 0x39)) this.skipNumber();
    else throw this.refuse("malformed");
  }

  // An opaque value is validated and carried, never interpreted. Its syntax is
  // the record's own — the same string reader, so an escape, a control byte or a
  // lone surrogate is judged identically at any depth — and what it is free to
  // spell, it keeps: the bytes between these two offsets are what a writer
  // re-emits. A number is walked, never converted, so a value no host type holds
  // survives the reader that carried it.
  skipString() {
    this.string();
  }

  someDigits() {
    let n = 0;
    while (this.at() >= 0x30 && this.at() <= 0x39) { this.pos++; n++; }
    if (n === 0) throw this.refuse("number_spelling");
  }

  skipNumber() {
    if (this.at() === 0x2d) this.pos++;
    const c = this.at();
    if (c === 0x30) this.pos++;
    else if (c > 0x30 && c <= 0x39) { while (this.at() >= 0x30 && this.at() <= 0x39) this.pos++; }
    else throw this.refuse("number_spelling");
    if (this.at() === 0x2e) { this.pos++; this.someDigits(); }
    if (this.at() === 0x65 || this.at() === 0x45) {
      this.pos++;
      if (this.at() === 0x2b || this.at() === 0x2d) this.pos++;
      this.someDigits();
    }
  }

  skipContainer() {
    const opener = this.at();
    const shut = opener === 0x7b ? 0x7d : 0x5d;
    this.enter();
    this.pos++;
    this.ws();
    const seen = new Set();
    if (this.at() !== shut) {
      for (;;) {
        this.ws();
        if (opener === 0x7b) {
          if (this.at() !== 0x22) throw this.refuse("malformed");
          const k = this.string();
          if (seen.has(k)) throw this.refuse("duplicate_key");
          seen.add(k);
          this.ws();
          if (this.at() !== 0x3a) throw this.refuse("malformed");
          this.pos++;
          this.ws();
        }
        this.skipValue();
        this.ws();
        if (this.at() !== 0x2c) break;
        this.pos++;
      }
    }
    if (this.at() !== shut) throw this.refuse("malformed");
    this.pos++;
    this.depth--;
  }
}

function readList(r, elem) {
  if (r.at() !== 0x5b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const out = [];
  r.ws();
  if (r.at() !== 0x5d) {
    for (;;) {
      r.ws();
      out.push(elem(r));
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x5d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  return out;
}

// Stable SDK key in an owner-issued history epoch. Scope is authenticated
// caller plus this service contract, never a caller-provided principal. Persist
// before send for restart recovery. Attempt is a nonnegative explicit retry
// number for the same key and epoch; zero is the original request. Attempt N+1
// is eligible only after attempt N failed terminally or was sealed (JOB-A7).
export function newRequestIdentity() {
  return { key: "", historyEpoch: "", attempt: 0n };
}

// Opaque kind-specific specification bytes, not a second tagged job Record.
// Equality includes kind, exact spec bytes and the set of required guarantees.
// Credentials are supplied at the authorized service boundary. Label is the
// caller's display text for the operation, 1 to 256 UTF-8 bytes after trimming
// on one line; an empty label is absent, and an invalid one makes Submit
// invalid. It is outside equality and fixed at acceptance (JOB-A12).
export function newSubmission() {
  return { identity: newRequestIdentity(), kind: "", spec: new Uint8Array(0), requiredGuarantees: [], label: "" };
}

// Recoverable acceptance evidence. Retention is a minimum duration from
// original acceptance, never renewed by replay. Expiry does not end work,
// transfer ownership or authorize duplicate execution. IDs confer no authority.
export function newReceipt() {
  return { identity: newRequestIdentity(), logicalOwner: "", operationId: "", acceptedGuarantees: [], historyRetentionMs: 0n };
}

// Accepted requires a receipt; other outcomes forbid one. Definite
// nonacceptance requires authoritative sealed evidence preventing any delayed
// acceptance of this identity. Absence, timeout, expired history and access
// denial are insufficient. Unavailable means a required policy decision could
// not be obtained: no admission effect and no seal were recorded, and the same
// identity may be presented again (JOB-A9).
export function newAcceptanceResult() {
  return { outcome: "", receipt: null, reason: "" };
}

// Owner-issued acceptance epoch and minimum reconciliation retention. After
// closing an epoch the owner fences all its submissions, including delayed
// ones. This does not assert that old unknown work was never accepted. Result
// retention is the provider's declared minimum time, in milliseconds after
// completion, that complete result bytes stay readable; zero declares none
// (JOB-A11).
export function newHistoryWindow() {
  return { logicalOwner: "", historyEpoch: "", minimumRetentionMs: 0n, resultRetentionMs: 0n };
}

// Requested acknowledges cancellation intent, not stopped effects. Completion
// may win the race; observe the existing operation for its terminal result.
// Unavailable records no intent because a required policy decision could not be
// obtained; the request may be repeated.
export function newCancellationResult() {
  return { outcome: "" };
}

// Advisory nonnegative progress. Zero total means unknown. Progress does not
// authorize delivery or imply completion.
export function newWorkProgress() {
  return { done: 0n, total: 0n };
}

// Last-attempt failure. Unknown classification remains unknown; do not infer it
// from message text. Retryable failure can coexist with pending work. Permanent
// classification means the provider will not try this operation again and its
// state is failed. Cause is the provider's typed reason when known; empty means
// unreported, and an unrecognized cause is treated as other.
export function newWorkFailure() {
  return { classification: "", message: "", cause: "" };
}

// Receipt binds original request and logical owner. Cancellation requested is
// intent, not stopped effects. Progress and last-attempt failure are advisory;
// no provider paths are exposed, and the label is display text, never a path or
// a result file name. Label is the stored display label: the caller's, or one
// the kind's provider derived at acceptance, when label_derived is true. It is
// absent when neither exists (JOB-A12). Waiting is the word the kind's provider
// reports for accepted, unfinished work held by a condition the submission set,
// such as network:metered; empty when nothing holds it. It is advisory and
// never a failure (JOB-A15).
export function newOperationSnapshot() {
  return { receipt: newReceipt(), state: "", progress: newWorkProgress(), cancellationRequested: false, failure: null, label: "", labelDerived: false, waiting: "" };
}

// Exactly observed carries a snapshot; all other outcomes forbid it. Absent
// identities are unknown and observation never seals them. Definite
// nonacceptance requires an existing authoritative seal. Already accepted
// journals may be recovered. Unavailable means a required policy decision could
// not be obtained and no state was read or changed (JOB-A9).
export function newObservationResult() {
  return { outcome: "", snapshot: null };
}

// Complete immutable result bytes bound to the original receipt. Offset equals
// requested nonnegative offset and is at most nonnegative total. Data length is
// at most requested max_bytes and total-offset. EOF is true exactly when offset
// plus data length equals total, including an empty complete result. Data is
// nonempty unless offset equals total and EOF is true. Missing data and errors
// never imply EOF.
export function newResultChunk() {
  return { receipt: newReceipt(), offset: 0n, total: 0n, data: new Uint8Array(0), eof: false };
}

// Exactly data carries a chunk; other outcomes forbid it. Only complete
// immutable results produce data. Incomplete work is not_ready; missing
// completed bytes are unavailable. Unsupported access, unknown identity,
// forbidden access and invalid bounds remain distinct.
export function newResultRead() {
  return { outcome: "", chunk: null };
}

// Caller-scoped accepted-operation observations without paths. Only page
// carries snapshots. A noncomplete page always has a next cursor, even when no
// own operations were scanned. Complete pages have empty next. Refusals carry
// no snapshots, empty next and complete=false. Directory traversal is a weak
// live view: concurrent insertions/removals can be omitted or repeated, not a
// stable transaction snapshot. An unchanged tree is fully traversable. Large
// failure diagnostics may be replaced by a bounded generic message.
export function newInventoryPage() {
  return { outcome: "", snapshots: [], next: "", complete: false };
}

// Requested acknowledges cancellation intent recorded on the named operation,
// whichever scope accepted it; it is not stopped effects. Already_terminal
// names an operation that ended. Unknown names no operation of this provider.
// Invalid is a malformed operation id. Forbidden is an evaluated refusal of the
// caller's rule. Unavailable records no intent because the decision or the
// store could not be reached (JOB-A13).
export function newOperatorCancellation() {
  return { outcome: "" };
}

function newOARecoverableAcceptanceGetHistoryWindowArguments() {
  return { };
}

function newOARecoverableAcceptanceSubmitArguments() {
  return { submission: newSubmission() };
}

function newOARecoverableAcceptanceReconcileArguments() {
  return { identity: newRequestIdentity() };
}

function newOARecoverableAcceptanceCancelWorkArguments() {
  return { identity: newRequestIdentity() };
}

function newOAOperationControlObserveWorkArguments() {
  return { identity: newRequestIdentity() };
}

function newOAOperationControlReadResultArguments() {
  return { identity: newRequestIdentity(), offset: 0n, maxBytes: 0n };
}

function newOAJobInventoryListWorkArguments() {
  return { cursor: "", limit: 0n };
}

function newOAJobOperatorListAccountWorkArguments() {
  return { cursor: "", limit: 0n };
}

function newOAJobOperatorCancelOperationArguments() {
  return { operationId: "" };
}

function newOAServiceFrame() {
  return { version: 0, service: "", method: "", arguments: "" };
}

function newOAServiceReply() {
  return { version: 0, service: "", method: "", ok: false, payload: "" };
}

function newOAServiceError() {
  return { code: "", message: "" };
}

function newOARecoverableAcceptanceGetHistoryWindowResult() {
  return { value: newHistoryWindow() };
}

function newOARecoverableAcceptanceSubmitResult() {
  return { value: newAcceptanceResult() };
}

function newOARecoverableAcceptanceReconcileResult() {
  return { value: newAcceptanceResult() };
}

function newOARecoverableAcceptanceCancelWorkResult() {
  return { value: newCancellationResult() };
}

function newOAOperationControlObserveWorkResult() {
  return { value: newObservationResult() };
}

function newOAOperationControlReadResultResult() {
  return { value: newResultRead() };
}

function newOAJobInventoryListWorkResult() {
  return { value: newInventoryPage() };
}

function newOAJobOperatorListAccountWorkResult() {
  return { value: newInventoryPage() };
}

function newOAJobOperatorCancelOperationResult() {
  return { value: newOperatorCancellation() };
}

function readRequestIdentity(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newRequestIdentity();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "key") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.key = r.string();
      } else if (key === "history_epoch") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.historyEpoch = r.string();
      } else if (key === "attempt") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.attempt = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function readSubmission(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newSubmission();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "identity") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.identity = readRequestIdentity(r);
      } else if (key === "kind") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.kind = r.string();
      } else if (key === "spec") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.spec = readBinary(r);
      } else if (key === "required_guarantees") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.requiredGuarantees = r.strList();
      } else if (key === "label") {
        if (seen & 16) throw r.refuse("duplicate_field");
        seen |= 16;
        v.label = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 15) >>> 0) !== 15) throw r.refuse("missing_field");
  return v;
}

function readReceipt(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newReceipt();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "identity") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.identity = readRequestIdentity(r);
      } else if (key === "logical_owner") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.logicalOwner = r.string();
      } else if (key === "operation_id") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.operationId = r.string();
      } else if (key === "accepted_guarantees") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.acceptedGuarantees = r.strList();
      } else if (key === "history_retention_ms") {
        if (seen & 16) throw r.refuse("duplicate_field");
        seen |= 16;
        v.historyRetentionMs = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 31) >>> 0) !== 31) throw r.refuse("missing_field");
  return v;
}

function readAcceptanceResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newAcceptanceResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "outcome") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.outcome = r.string();
      } else if (key === "receipt") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.receipt = readReceipt(r);
      } else if (key === "reason") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.reason = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 5) >>> 0) !== 5) throw r.refuse("missing_field");
    if (v.outcome !== "accepted" && v.outcome !== "definitely_not_accepted" && v.outcome !== "unknown" && v.outcome !== "key_conflict" && v.outcome !== "forbidden" && v.outcome !== "invalid" && v.outcome !== "unavailable") { throw r.refuse("bad_enum"); }
  return v;
}

function readHistoryWindow(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newHistoryWindow();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "logical_owner") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.logicalOwner = r.string();
      } else if (key === "history_epoch") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.historyEpoch = r.string();
      } else if (key === "minimum_retention_ms") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.minimumRetentionMs = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else if (key === "result_retention_ms") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.resultRetentionMs = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 7) >>> 0) !== 7) throw r.refuse("missing_field");
  return v;
}

function readCancellationResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newCancellationResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "outcome") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.outcome = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
    if (v.outcome !== "requested" && v.outcome !== "already_terminal" && v.outcome !== "unknown" && v.outcome !== "forbidden" && v.outcome !== "unsupported" && v.outcome !== "unavailable") { throw r.refuse("bad_enum"); }
  return v;
}

function readWorkProgress(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newWorkProgress();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "done") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.done = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else if (key === "total") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.total = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function readWorkFailure(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newWorkFailure();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "classification") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.classification = r.string();
      } else if (key === "message") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.message = r.string();
      } else if (key === "cause") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.cause = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
    if (v.classification !== "retryable" && v.classification !== "permanent" && v.classification !== "unknown") { throw r.refuse("bad_enum"); }
  return v;
}

function readOperationSnapshot(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOperationSnapshot();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "receipt") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.receipt = readReceipt(r);
      } else if (key === "state") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.state = r.string();
      } else if (key === "progress") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.progress = readWorkProgress(r);
      } else if (key === "cancellation_requested") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.cancellationRequested = r.boolean();
      } else if (key === "failure") {
        if (seen & 16) throw r.refuse("duplicate_field");
        seen |= 16;
        v.failure = readWorkFailure(r);
      } else if (key === "label") {
        if (seen & 32) throw r.refuse("duplicate_field");
        seen |= 32;
        v.label = r.string();
      } else if (key === "label_derived") {
        if (seen & 64) throw r.refuse("duplicate_field");
        seen |= 64;
        v.labelDerived = r.boolean();
      } else if (key === "waiting") {
        if (seen & 128) throw r.refuse("duplicate_field");
        seen |= 128;
        v.waiting = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 15) >>> 0) !== 15) throw r.refuse("missing_field");
    if (v.state !== "pending" && v.state !== "running" && v.state !== "transferred" && v.state !== "complete" && v.state !== "failed" && v.state !== "cancelled") { throw r.refuse("bad_enum"); }
  return v;
}

function readObservationResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newObservationResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "outcome") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.outcome = r.string();
      } else if (key === "snapshot") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.snapshot = readOperationSnapshot(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
    if (v.outcome !== "observed" && v.outcome !== "unknown" && v.outcome !== "forbidden" && v.outcome !== "invalid" && v.outcome !== "definitely_not_accepted" && v.outcome !== "unavailable") { throw r.refuse("bad_enum"); }
  return v;
}

function readResultChunk(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newResultChunk();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "receipt") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.receipt = readReceipt(r);
      } else if (key === "offset") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.offset = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else if (key === "total") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.total = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else if (key === "data") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.data = readBinary(r);
      } else if (key === "eof") {
        if (seen & 16) throw r.refuse("duplicate_field");
        seen |= 16;
        v.eof = r.boolean();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 31) >>> 0) !== 31) throw r.refuse("missing_field");
  return v;
}

function readResultRead(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newResultRead();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "outcome") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.outcome = r.string();
      } else if (key === "chunk") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.chunk = readResultChunk(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
    if (v.outcome !== "data" && v.outcome !== "not_ready" && v.outcome !== "unavailable" && v.outcome !== "unsupported" && v.outcome !== "unknown" && v.outcome !== "forbidden" && v.outcome !== "invalid") { throw r.refuse("bad_enum"); }
  return v;
}

function readInventoryPage(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newInventoryPage();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "outcome") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.outcome = r.string();
      } else if (key === "snapshots") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.snapshots = readList(r, readOperationSnapshot);
      } else if (key === "next") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.next = r.string();
      } else if (key === "complete") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.complete = r.boolean();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 15) >>> 0) !== 15) throw r.refuse("missing_field");
    if (v.outcome !== "page" && v.outcome !== "gap" && v.outcome !== "forbidden" && v.outcome !== "invalid" && v.outcome !== "unavailable") { throw r.refuse("bad_enum"); }
  return v;
}

function readOperatorCancellation(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOperatorCancellation();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "outcome") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.outcome = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
    if (v.outcome !== "requested" && v.outcome !== "already_terminal" && v.outcome !== "unknown" && v.outcome !== "forbidden" && v.outcome !== "invalid" && v.outcome !== "unavailable") { throw r.refuse("bad_enum"); }
  return v;
}

function readOARecoverableAcceptanceGetHistoryWindowArguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOARecoverableAcceptanceGetHistoryWindowArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (false) {
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  return v;
}

function readOARecoverableAcceptanceSubmitArguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOARecoverableAcceptanceSubmitArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "submission") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.submission = readSubmission(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function readOARecoverableAcceptanceReconcileArguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOARecoverableAcceptanceReconcileArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "identity") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.identity = readRequestIdentity(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function readOARecoverableAcceptanceCancelWorkArguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOARecoverableAcceptanceCancelWorkArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "identity") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.identity = readRequestIdentity(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function readOAOperationControlObserveWorkArguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAOperationControlObserveWorkArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "identity") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.identity = readRequestIdentity(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function readOAOperationControlReadResultArguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAOperationControlReadResultArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "identity") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.identity = readRequestIdentity(r);
      } else if (key === "offset") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.offset = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else if (key === "max_bytes") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.maxBytes = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 7) >>> 0) !== 7) throw r.refuse("missing_field");
  return v;
}

function readOAJobInventoryListWorkArguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAJobInventoryListWorkArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "cursor") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.cursor = r.string();
      } else if (key === "limit") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.limit = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function readOAJobOperatorListAccountWorkArguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAJobOperatorListAccountWorkArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "cursor") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.cursor = r.string();
      } else if (key === "limit") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.limit = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function readOAJobOperatorCancelOperationArguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAJobOperatorCancelOperationArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "operation_id") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.operationId = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function readOAServiceFrame(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAServiceFrame();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "version") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.version = Number(r.integer(-2147483648n, 2147483647n));
      } else if (key === "service") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.service = r.string();
      } else if (key === "method") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.method = r.string();
      } else if (key === "arguments") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.arguments = r.rawValue();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 15) >>> 0) !== 15) throw r.refuse("missing_field");
  return v;
}

function readOAServiceReply(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAServiceReply();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "version") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.version = Number(r.integer(-2147483648n, 2147483647n));
      } else if (key === "service") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.service = r.string();
      } else if (key === "method") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.method = r.string();
      } else if (key === "ok") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.ok = r.boolean();
      } else if (key === "payload") {
        if (seen & 16) throw r.refuse("duplicate_field");
        seen |= 16;
        v.payload = r.rawValue();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 31) >>> 0) !== 31) throw r.refuse("missing_field");
  return v;
}

function readOAServiceError(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAServiceError();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "code") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.code = r.string();
      } else if (key === "message") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.message = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function readOARecoverableAcceptanceGetHistoryWindowResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOARecoverableAcceptanceGetHistoryWindowResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = readHistoryWindow(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function readOARecoverableAcceptanceSubmitResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOARecoverableAcceptanceSubmitResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = readAcceptanceResult(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function readOARecoverableAcceptanceReconcileResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOARecoverableAcceptanceReconcileResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = readAcceptanceResult(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function readOARecoverableAcceptanceCancelWorkResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOARecoverableAcceptanceCancelWorkResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = readCancellationResult(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function readOAOperationControlObserveWorkResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAOperationControlObserveWorkResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = readObservationResult(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function readOAOperationControlReadResultResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAOperationControlReadResultResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = readResultRead(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function readOAJobInventoryListWorkResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAJobInventoryListWorkResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = readInventoryPage(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function readOAJobOperatorListAccountWorkResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAJobOperatorListAccountWorkResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = readInventoryPage(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function readOAJobOperatorCancelOperationResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAJobOperatorCancelOperationResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = readOperatorCancellation(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

export function decode(data) {
  const r = new Reader(data);
  r.ws();
  const v = readAcceptanceResult(r);
  r.ws();
  if (r.pos < r.buf.length) throw r.refuse("trailing_bytes");
  return v;
}

// refusals is in the order two of them are chosen between.
const refusals = ["malformed", "bad_string", "number_spelling", "wrong_type", "depth_exceeded", "duplicate_key", "duplicate_field", "unknown_field", "missing_field", "bad_binary", "bad_enum", "trailing_bytes"];

function refusalRank(word) {
  return refusals.indexOf(word);
}

export class DispatchError extends Error {
  constructor(code) { super(code); this.name = "DispatchError"; this.code = code; }
}
export class ServiceError extends Error {
  constructor(code, message = "") { super(message || code); this.name = "ServiceError"; this.code = code; }
}
function _serviceDecode(decoder, frame, depth) {
  const reader = new Reader(typeof frame === "string" ? ENC.encode(frame) : frame);
  reader.depth = depth; reader.ws();
  const value = decoder(reader); reader.ws();
  if (reader.pos !== reader.buf.length) throw reader.refuse("trailing_bytes");
  return value;
}
function _serviceEncode(encoder, value, depth) {
  const out = new Out(); encoder(out, value, depth); return out.bytes();
}
function _serviceCheck(kind, value, depth = 0) {
  if (depth > DEPTH_LIMIT) throw new Refusal("depth_exceeded", 0);
  let valid = false;
  if (kind === "string") {
    valid = typeof value === "string";
    if (valid) for (const ch of value) {
      const cp = ch.codePointAt(0);
      if (cp >= 0xd800 && cp <= 0xdfff) throw new Refusal("bad_string", 0);
    }
  } else if (kind === "i32") {
    valid = typeof value === "number" && Number.isInteger(value) && value >= -2147483648 && value <= 2147483647;
  } else if (kind === "i64") {
    valid = typeof value === "bigint" && value >= -9223372036854775808n && value <= 9223372036854775807n;
  } else if (kind === "bool") valid = typeof value === "boolean";
  else if (kind === "binary") valid = value instanceof Uint8Array;
  else if (kind === "json") {
    valid = typeof value === "string" || value instanceof Uint8Array;
    if (valid) { const r = new Reader(typeof value === "string" ? ENC.encode(value) : value); r.depth = depth; r.ws(); r.rawValue(); r.ws(); if (r.pos !== r.buf.length) throw r.refuse("trailing_bytes"); }
  } else if (kind.startsWith("list<")) {
    valid = Array.isArray(value);
    if (valid) for (const item of value) _serviceCheck(kind.slice(5,-1), item, depth + 1);
  } else if (kind.startsWith("map<string,")) {
    valid = value !== null && typeof value === "object" && !Array.isArray(value);
    if (valid) for (const [key,item] of Object.entries(value)) { _serviceCheck("string",key,depth+1); _serviceCheck(kind.slice(11,-1),item,depth+1); }
  } else {
    const fields = _serviceRecords[kind];
    valid = fields !== undefined && value !== null && typeof value === "object" && !Array.isArray(value);
    if (valid) for (const [name,type,omit] of fields) {
      if (!Object.hasOwn(value,name)) throw new Refusal("missing_field",0);
      const item = value[name];
      if (omit === "absent" && item === null) continue;
      _serviceCheck(type,item,depth+1);
    }
  }
  if (!valid) throw new Refusal("wrong_type", 0);
}

const _serviceRecords = Object.create(null);
_serviceRecords["RequestIdentity"] = [["key","string","never"],["historyEpoch","string","never"],["attempt","i64","zero"],];
_serviceRecords["Submission"] = [["identity","RequestIdentity","never"],["kind","string","never"],["spec","binary","never"],["requiredGuarantees","list<string>","never"],["label","string","absent"],];
_serviceRecords["Receipt"] = [["identity","RequestIdentity","never"],["logicalOwner","string","never"],["operationId","string","never"],["acceptedGuarantees","list<string>","never"],["historyRetentionMs","i64","never"],];
_serviceRecords["AcceptanceResult"] = [["outcome","string","never"],["receipt","Receipt","absent"],["reason","string","never"],];
_serviceRecords["HistoryWindow"] = [["logicalOwner","string","never"],["historyEpoch","string","never"],["minimumRetentionMs","i64","never"],["resultRetentionMs","i64","zero"],];
_serviceRecords["CancellationResult"] = [["outcome","string","never"],];
_serviceRecords["WorkProgress"] = [["done","i64","never"],["total","i64","never"],];
_serviceRecords["WorkFailure"] = [["classification","string","never"],["message","string","never"],["cause","string","zero"],];
_serviceRecords["OperationSnapshot"] = [["receipt","Receipt","never"],["state","string","never"],["progress","WorkProgress","never"],["cancellationRequested","bool","never"],["failure","WorkFailure","absent"],["label","string","absent"],["labelDerived","bool","zero"],["waiting","string","zero"],];
_serviceRecords["ObservationResult"] = [["outcome","string","never"],["snapshot","OperationSnapshot","absent"],];
_serviceRecords["ResultChunk"] = [["receipt","Receipt","never"],["offset","i64","never"],["total","i64","never"],["data","binary","never"],["eof","bool","never"],];
_serviceRecords["ResultRead"] = [["outcome","string","never"],["chunk","ResultChunk","absent"],];
_serviceRecords["InventoryPage"] = [["outcome","string","never"],["snapshots","list<OperationSnapshot>","never"],["next","string","never"],["complete","bool","never"],];
_serviceRecords["OperatorCancellation"] = [["outcome","string","never"],];
_serviceRecords["OARecoverableAcceptanceGetHistoryWindowArguments"] = [];
_serviceRecords["OARecoverableAcceptanceSubmitArguments"] = [["submission","Submission","never"],];
_serviceRecords["OARecoverableAcceptanceReconcileArguments"] = [["identity","RequestIdentity","never"],];
_serviceRecords["OARecoverableAcceptanceCancelWorkArguments"] = [["identity","RequestIdentity","never"],];
_serviceRecords["OAOperationControlObserveWorkArguments"] = [["identity","RequestIdentity","never"],];
_serviceRecords["OAOperationControlReadResultArguments"] = [["identity","RequestIdentity","never"],["offset","i64","never"],["maxBytes","i64","never"],];
_serviceRecords["OAJobInventoryListWorkArguments"] = [["cursor","string","never"],["limit","i64","never"],];
_serviceRecords["OAJobOperatorListAccountWorkArguments"] = [["cursor","string","never"],["limit","i64","never"],];
_serviceRecords["OAJobOperatorCancelOperationArguments"] = [["operationId","string","never"],];
_serviceRecords["OAServiceFrame"] = [["version","i32","never"],["service","string","never"],["method","string","never"],["arguments","json","never"],];
_serviceRecords["OAServiceReply"] = [["version","i32","never"],["service","string","never"],["method","string","never"],["ok","bool","never"],["payload","json","never"],];
_serviceRecords["OAServiceError"] = [["code","string","never"],["message","string","never"],];
_serviceRecords["OARecoverableAcceptanceGetHistoryWindowResult"] = [["value","HistoryWindow","never"],];
_serviceRecords["OARecoverableAcceptanceSubmitResult"] = [["value","AcceptanceResult","never"],];
_serviceRecords["OARecoverableAcceptanceReconcileResult"] = [["value","AcceptanceResult","never"],];
_serviceRecords["OARecoverableAcceptanceCancelWorkResult"] = [["value","CancellationResult","never"],];
_serviceRecords["OAOperationControlObserveWorkResult"] = [["value","ObservationResult","never"],];
_serviceRecords["OAOperationControlReadResultResult"] = [["value","ResultRead","never"],];
_serviceRecords["OAJobInventoryListWorkResult"] = [["value","InventoryPage","never"],];
_serviceRecords["OAJobOperatorListAccountWorkResult"] = [["value","InventoryPage","never"],];
_serviceRecords["OAJobOperatorCancelOperationResult"] = [["value","OperatorCancellation","never"],];

function _serviceRequest(service, method, argumentsBytes) {
  return _serviceEncode(writeOAServiceFrame, {
    version:1, service, method, arguments:new TextDecoder("utf-8",{fatal:true}).decode(argumentsBytes)
  },0);
}

function _serviceResponse(frame, service, method) {
  if (!(frame instanceof Uint8Array)) throw new TypeError("transport frame must be Uint8Array");
  const reply = _serviceDecode(readOAServiceReply, frame, 0);
  if (reply.version !== 1) throw new DispatchError("unknown_version");
  if (reply.service !== service || reply.method !== method) throw new DispatchError("mismatched_response");
  if (!reply.ok) {
    const error = _serviceDecode(readOAServiceError, reply.payload, 1);
    if (!error.code) throw new DispatchError("invalid_error");
    throw new ServiceError(error.code, error.message);
  }
  return reply.payload;
}

export class RecoverableAcceptanceClient {
  constructor(transport) { this._transport = transport; }

  async getHistoryWindow() {
    const _args = newOARecoverableAcceptanceGetHistoryWindowArguments();
    _serviceCheck("OARecoverableAcceptanceGetHistoryWindowArguments", _args);
    const _payload = _serviceEncode(writeOARecoverableAcceptanceGetHistoryWindowArguments, _args, 1);
    _serviceDecode(readOARecoverableAcceptanceGetHistoryWindowArguments, _payload, 1);
    const _request = _serviceRequest("abstraction.job/acceptance@1", "GetHistoryWindow", _payload);
    const _reply = _serviceResponse(await this._transport.exchangeFrame(_request), "abstraction.job/acceptance@1", "GetHistoryWindow");
    const _result = _serviceDecode(readOARecoverableAcceptanceGetHistoryWindowResult, _reply, 1);
    return _result.value;
  }

  async submit(submission) {
    const _args = newOARecoverableAcceptanceSubmitArguments();
    _args.submission = submission;
    _serviceCheck("OARecoverableAcceptanceSubmitArguments", _args);
    const _payload = _serviceEncode(writeOARecoverableAcceptanceSubmitArguments, _args, 1);
    _serviceDecode(readOARecoverableAcceptanceSubmitArguments, _payload, 1);
    const _request = _serviceRequest("abstraction.job/acceptance@1", "Submit", _payload);
    const _reply = _serviceResponse(await this._transport.exchangeFrame(_request), "abstraction.job/acceptance@1", "Submit");
    const _result = _serviceDecode(readOARecoverableAcceptanceSubmitResult, _reply, 1);
    return _result.value;
  }

  async reconcile(identity) {
    const _args = newOARecoverableAcceptanceReconcileArguments();
    _args.identity = identity;
    _serviceCheck("OARecoverableAcceptanceReconcileArguments", _args);
    const _payload = _serviceEncode(writeOARecoverableAcceptanceReconcileArguments, _args, 1);
    _serviceDecode(readOARecoverableAcceptanceReconcileArguments, _payload, 1);
    const _request = _serviceRequest("abstraction.job/acceptance@1", "Reconcile", _payload);
    const _reply = _serviceResponse(await this._transport.exchangeFrame(_request), "abstraction.job/acceptance@1", "Reconcile");
    const _result = _serviceDecode(readOARecoverableAcceptanceReconcileResult, _reply, 1);
    return _result.value;
  }

  async cancelWork(identity) {
    const _args = newOARecoverableAcceptanceCancelWorkArguments();
    _args.identity = identity;
    _serviceCheck("OARecoverableAcceptanceCancelWorkArguments", _args);
    const _payload = _serviceEncode(writeOARecoverableAcceptanceCancelWorkArguments, _args, 1);
    _serviceDecode(readOARecoverableAcceptanceCancelWorkArguments, _payload, 1);
    const _request = _serviceRequest("abstraction.job/acceptance@1", "CancelWork", _payload);
    const _reply = _serviceResponse(await this._transport.exchangeFrame(_request), "abstraction.job/acceptance@1", "CancelWork");
    const _result = _serviceDecode(readOARecoverableAcceptanceCancelWorkResult, _reply, 1);
    return _result.value;
  }
}
export const RecoverableAcceptanceService = Object.freeze({wireName:"abstraction.job/acceptance@1",Client:RecoverableAcceptanceClient});

export class OperationControlClient {
  constructor(transport) { this._transport = transport; }

  async observeWork(identity) {
    const _args = newOAOperationControlObserveWorkArguments();
    _args.identity = identity;
    _serviceCheck("OAOperationControlObserveWorkArguments", _args);
    const _payload = _serviceEncode(writeOAOperationControlObserveWorkArguments, _args, 1);
    _serviceDecode(readOAOperationControlObserveWorkArguments, _payload, 1);
    const _request = _serviceRequest("abstraction.job/operations@1", "ObserveWork", _payload);
    const _reply = _serviceResponse(await this._transport.exchangeFrame(_request), "abstraction.job/operations@1", "ObserveWork");
    const _result = _serviceDecode(readOAOperationControlObserveWorkResult, _reply, 1);
    return _result.value;
  }

  async readResult(identity, offset, maxBytes) {
    const _args = newOAOperationControlReadResultArguments();
    _args.identity = identity;
    _args.offset = offset;
    _args.maxBytes = maxBytes;
    _serviceCheck("OAOperationControlReadResultArguments", _args);
    const _payload = _serviceEncode(writeOAOperationControlReadResultArguments, _args, 1);
    _serviceDecode(readOAOperationControlReadResultArguments, _payload, 1);
    const _request = _serviceRequest("abstraction.job/operations@1", "ReadResult", _payload);
    const _reply = _serviceResponse(await this._transport.exchangeFrame(_request), "abstraction.job/operations@1", "ReadResult");
    const _result = _serviceDecode(readOAOperationControlReadResultResult, _reply, 1);
    return _result.value;
  }
}
export const OperationControlService = Object.freeze({wireName:"abstraction.job/operations@1",Client:OperationControlClient});

export class JobInventoryClient {
  constructor(transport) { this._transport = transport; }

  async listWork(cursor, limit) {
    const _args = newOAJobInventoryListWorkArguments();
    _args.cursor = cursor;
    _args.limit = limit;
    _serviceCheck("OAJobInventoryListWorkArguments", _args);
    const _payload = _serviceEncode(writeOAJobInventoryListWorkArguments, _args, 1);
    _serviceDecode(readOAJobInventoryListWorkArguments, _payload, 1);
    const _request = _serviceRequest("abstraction.job/inventory@1", "ListWork", _payload);
    const _reply = _serviceResponse(await this._transport.exchangeFrame(_request), "abstraction.job/inventory@1", "ListWork");
    const _result = _serviceDecode(readOAJobInventoryListWorkResult, _reply, 1);
    return _result.value;
  }
}
export const JobInventoryService = Object.freeze({wireName:"abstraction.job/inventory@1",Client:JobInventoryClient});

export class JobOperatorClient {
  constructor(transport) { this._transport = transport; }

  async listAccountWork(cursor, limit) {
    const _args = newOAJobOperatorListAccountWorkArguments();
    _args.cursor = cursor;
    _args.limit = limit;
    _serviceCheck("OAJobOperatorListAccountWorkArguments", _args);
    const _payload = _serviceEncode(writeOAJobOperatorListAccountWorkArguments, _args, 1);
    _serviceDecode(readOAJobOperatorListAccountWorkArguments, _payload, 1);
    const _request = _serviceRequest("abstraction.job/operator@1", "ListAccountWork", _payload);
    const _reply = _serviceResponse(await this._transport.exchangeFrame(_request), "abstraction.job/operator@1", "ListAccountWork");
    const _result = _serviceDecode(readOAJobOperatorListAccountWorkResult, _reply, 1);
    return _result.value;
  }

  async cancelOperation(operationId) {
    const _args = newOAJobOperatorCancelOperationArguments();
    _args.operationId = operationId;
    _serviceCheck("OAJobOperatorCancelOperationArguments", _args);
    const _payload = _serviceEncode(writeOAJobOperatorCancelOperationArguments, _args, 1);
    _serviceDecode(readOAJobOperatorCancelOperationArguments, _payload, 1);
    const _request = _serviceRequest("abstraction.job/operator@1", "CancelOperation", _payload);
    const _reply = _serviceResponse(await this._transport.exchangeFrame(_request), "abstraction.job/operator@1", "CancelOperation");
    const _result = _serviceDecode(readOAJobOperatorCancelOperationResult, _reply, 1);
    return _result.value;
  }
}
export const JobOperatorService = Object.freeze({wireName:"abstraction.job/operator@1",Client:JobOperatorClient});
