// Code generated by abstraction-idl from abstraction-job/acceptance.thrift. DO NOT EDIT.

#pragma once

#include <cstddef>
#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <string_view>
#include <vector>

namespace abstraction::job::acceptance {

using Raw = std::string;

inline void esc(std::string& out, const std::string& s);

inline void esc_byte(std::string& out, unsigned char c) {
    static const char* kHex = "0123456789abcdef";
    switch (c) {
        case '"': out += "\\\""; return;
        case '\\': out += "\\\\"; return;
        case 0x08: out += "\\b"; return;
        case 0x0c: out += "\\f"; return;
        case '\n': out += "\\n"; return;
        case '\r': out += "\\r"; return;
        case '\t': out += "\\t"; return;
        default: break;
    }
    if (c < 0x20) {
        out += "\\u00";
        out += kHex[c >> 4];
        out += kHex[c & 0x0F];
    } else {
        out += static_cast<char>(c);
    }
}

inline void num(std::string& out, std::int64_t n) { out += std::to_string(n); }

inline void pad(std::string& out, int depth) {
    out.append(static_cast<std::size_t>(depth) * 2, ' ');
}

inline void strs(std::string& out, const std::vector<std::string>& v, int depth) {
    if (v.empty()) { out += "[]"; return; }
    out += "[\n";
    for (std::size_t i = 0; i < v.size(); ++i) {
        pad(out, depth + 1);
        esc(out, v[i]);
        if (i + 1 < v.size()) out += ',';
        out += '\n';
    }
    pad(out, depth);
    out += ']';
}

inline bool ws(unsigned char c) { return c == ' ' || c == '\t' || c == '\n' || c == '\r'; }

inline void raw(std::string& out, const std::string& s, int depth) {
    const std::size_t n = s.size();
    for (std::size_t i = 0; i < n;) {
        const unsigned char c = static_cast<unsigned char>(s[i]);
        if (ws(c)) {
            ++i;
        } else if (c == '"') {
            std::size_t j = i + 1;
            while (j < n) {
                if (s[j] == '\\') { j += 2; continue; }
                if (s[j] == '"') { ++j; break; }
                ++j;
            }
            out.append(s, i, j - i);
            i = j;
        } else if (c == '{' || c == '[') {
            out += static_cast<char>(c);
            ++i;
            std::size_t j = i;
            while (j < n && ws(static_cast<unsigned char>(s[j]))) ++j;
            if (j < n && (s[j] == '}' || s[j] == ']')) {
                out += s[j];
                i = j + 1;
            } else {
                ++depth;
                out += '\n';
                pad(out, depth);
            }
        } else if (c == '}' || c == ']') {
            --depth;
            out += '\n';
            pad(out, depth);
            out += static_cast<char>(c);
            ++i;
        } else if (c == ',') {
            out += ",\n";
            pad(out, depth);
            ++i;
        } else if (c == ':') {
            out += ": ";
            ++i;
        } else {
            out += static_cast<char>(c);
            ++i;
        }
    }
}

// std::char_traits<char>::compare is specified to order by unsigned char, so a
// std::map<std::string, ...> already walks its keys in UTF-8 byte order — which
// is what the definition declares. Nothing sorts here because nothing needs to.
inline void rawmap(std::string& out, const std::map<std::string, Raw>& m, int depth) {
    if (m.empty()) { out += "{}"; return; }
    out += "{\n";
    std::size_t i = 0;
    for (const auto& kv : m) {
        pad(out, depth + 1);
        esc(out, kv.first);
        out += ": ";
        raw(out, kv.second, depth + 1);
        if (++i < m.size()) out += ',';
        out += '\n';
    }
    pad(out, depth);
    out += '}';
}

inline void esc(std::string& out, const std::string& s) {
    out += '"';
    for (unsigned char c : s) esc_byte(out, c);
    out += '"';
}

class Refusal : public std::runtime_error {
public:
    Refusal(const char* word, std::size_t offset)
        : std::runtime_error(std::string("refused: ") + word + " at byte " + std::to_string(offset)),
          word(word),
          offset(offset) {}
    const char* word;
    std::size_t offset;
};

inline std::string encode_binary(const std::vector<std::uint8_t>&);
inline std::vector<std::uint8_t> decode_binary(const std::string&);

inline const std::vector<std::string> kOutcomeNames = {"accepted", "definitely_not_accepted", "unknown", "key_conflict", "forbidden", "invalid"};
inline const std::string kOutcomeUnknown = "refuse";

inline const std::vector<std::string> kCancellationOutcomeNames = {"requested", "already_terminal", "unknown", "forbidden", "unsupported"};
inline const std::string kCancellationOutcomeUnknown = "refuse";

struct RequestIdentity {
    std::string key;
    std::string history_epoch;
};

struct Submission {
    RequestIdentity identity;
    std::string kind;
    std::vector<std::uint8_t> spec;
    std::vector<std::string> required_guarantees;
};

struct Receipt {
    RequestIdentity identity;
    std::string logical_owner;
    std::string operation_id;
    std::vector<std::string> accepted_guarantees;
    std::int64_t history_retention_ms = 0;
};

struct AcceptanceResult {
    std::string outcome;
    std::optional<Receipt> receipt;
    std::string reason;
};

struct HistoryWindow {
    std::string logical_owner;
    std::string history_epoch;
    std::int64_t minimum_retention_ms = 0;
};

struct CancellationResult {
    std::string outcome;
};

struct OARecoverableAcceptanceGetHistoryWindowArguments {
};

struct OARecoverableAcceptanceSubmitArguments {
    Submission submission;
};

struct OARecoverableAcceptanceReconcileArguments {
    RequestIdentity identity;
};

struct OARecoverableAcceptanceCancelWorkArguments {
    RequestIdentity identity;
};

struct OAServiceFrame {
    std::int32_t version = 0;
    std::string service;
    std::string method;
    Raw arguments;
};

struct OAServiceReply {
    std::int32_t version = 0;
    std::string service;
    std::string method;
    bool ok = false;
    Raw payload;
};

struct OAServiceError {
    std::string code;
    std::string message;
};

struct OARecoverableAcceptanceGetHistoryWindowResult {
    HistoryWindow value;
};

struct OARecoverableAcceptanceSubmitResult {
    AcceptanceResult value;
};

struct OARecoverableAcceptanceReconcileResult {
    AcceptanceResult value;
};

struct OARecoverableAcceptanceCancelWorkResult {
    CancellationResult value;
};

inline void enc_requestidentity(std::string& out, const RequestIdentity& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "key");
    out += ": ";
    esc(out, v.key);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "history_epoch");
    out += ": ";
    esc(out, v.history_epoch);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_submission(std::string& out, const Submission& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "identity");
    out += ": ";
    enc_requestidentity(out, v.identity, depth + 1);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "kind");
    out += ": ";
    esc(out, v.kind);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "spec");
    out += ": ";
    esc(out, encode_binary(v.spec));
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "required_guarantees");
    out += ": ";
    strs(out, v.required_guarantees, depth + 1);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_receipt(std::string& out, const Receipt& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "identity");
    out += ": ";
    enc_requestidentity(out, v.identity, depth + 1);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "logical_owner");
    out += ": ";
    esc(out, v.logical_owner);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "operation_id");
    out += ": ";
    esc(out, v.operation_id);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "accepted_guarantees");
    out += ": ";
    strs(out, v.accepted_guarantees, depth + 1);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "history_retention_ms");
    out += ": ";
    num(out, v.history_retention_ms);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_acceptanceresult(std::string& out, const AcceptanceResult& v, int depth) {
    if (v.outcome != "accepted" && v.outcome != "definitely_not_accepted" && v.outcome != "unknown" && v.outcome != "key_conflict" && v.outcome != "forbidden" && v.outcome != "invalid") { throw Refusal("bad_enum",0); }
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "outcome");
    out += ": ";
    esc(out, v.outcome);
    if (v.receipt.has_value()) {
        out += ',';
        out += '\n';
        pad(out, depth + 1);
        esc(out, "receipt");
        out += ": ";
        enc_receipt(out, *v.receipt, depth + 1);
    }
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "reason");
    out += ": ";
    esc(out, v.reason);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_historywindow(std::string& out, const HistoryWindow& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "logical_owner");
    out += ": ";
    esc(out, v.logical_owner);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "history_epoch");
    out += ": ";
    esc(out, v.history_epoch);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "minimum_retention_ms");
    out += ": ";
    num(out, v.minimum_retention_ms);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_cancellationresult(std::string& out, const CancellationResult& v, int depth) {
    if (v.outcome != "requested" && v.outcome != "already_terminal" && v.outcome != "unknown" && v.outcome != "forbidden" && v.outcome != "unsupported") { throw Refusal("bad_enum",0); }
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "outcome");
    out += ": ";
    esc(out, v.outcome);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oarecoverableacceptancegethistorywindowarguments(std::string& out, const OARecoverableAcceptanceGetHistoryWindowArguments& v, int depth) {
    out += '{';
    out += '}';
}

inline void enc_oarecoverableacceptancesubmitarguments(std::string& out, const OARecoverableAcceptanceSubmitArguments& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "submission");
    out += ": ";
    enc_submission(out, v.submission, depth + 1);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oarecoverableacceptancereconcilearguments(std::string& out, const OARecoverableAcceptanceReconcileArguments& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "identity");
    out += ": ";
    enc_requestidentity(out, v.identity, depth + 1);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oarecoverableacceptancecancelworkarguments(std::string& out, const OARecoverableAcceptanceCancelWorkArguments& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "identity");
    out += ": ";
    enc_requestidentity(out, v.identity, depth + 1);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oaserviceframe(std::string& out, const OAServiceFrame& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "version");
    out += ": ";
    num(out, v.version);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "service");
    out += ": ";
    esc(out, v.service);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "method");
    out += ": ";
    esc(out, v.method);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "arguments");
    out += ": ";
    out += v.arguments;
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oaservicereply(std::string& out, const OAServiceReply& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "version");
    out += ": ";
    num(out, v.version);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "service");
    out += ": ";
    esc(out, v.service);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "method");
    out += ": ";
    esc(out, v.method);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "ok");
    out += ": ";
    out += v.ok ? "true" : "false";
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "payload");
    out += ": ";
    out += v.payload;
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oaserviceerror(std::string& out, const OAServiceError& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "code");
    out += ": ";
    esc(out, v.code);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "message");
    out += ": ";
    esc(out, v.message);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oarecoverableacceptancegethistorywindowresult(std::string& out, const OARecoverableAcceptanceGetHistoryWindowResult& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "value");
    out += ": ";
    enc_historywindow(out, v.value, depth + 1);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oarecoverableacceptancesubmitresult(std::string& out, const OARecoverableAcceptanceSubmitResult& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "value");
    out += ": ";
    enc_acceptanceresult(out, v.value, depth + 1);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oarecoverableacceptancereconcileresult(std::string& out, const OARecoverableAcceptanceReconcileResult& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "value");
    out += ": ";
    enc_acceptanceresult(out, v.value, depth + 1);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oarecoverableacceptancecancelworkresult(std::string& out, const OARecoverableAcceptanceCancelWorkResult& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "value");
    out += ": ";
    enc_cancellationresult(out, v.value, depth + 1);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline std::string encode(const AcceptanceResult& v) {
    std::string out;
    enc_acceptanceresult(out, v, 0);
    out += '\n';
    return out;
}

inline constexpr int kDepthLimit = 64;
inline constexpr std::size_t kI64Digits = 19;



inline void append_rune(std::string& out, std::uint32_t cp) {
    if (cp < 0x80) {
        out += static_cast<char>(cp);
    } else if (cp < 0x800) {
        out += static_cast<char>(0xC0 | (cp >> 6));
        out += static_cast<char>(0x80 | (cp & 0x3F));
    } else if (cp < 0x10000) {
        out += static_cast<char>(0xE0 | (cp >> 12));
        out += static_cast<char>(0x80 | ((cp >> 6) & 0x3F));
        out += static_cast<char>(0x80 | (cp & 0x3F));
    } else {
        out += static_cast<char>(0xF0 | (cp >> 18));
        out += static_cast<char>(0x80 | ((cp >> 12) & 0x3F));
        out += static_cast<char>(0x80 | ((cp >> 6) & 0x3F));
        out += static_cast<char>(0x80 | (cp & 0x3F));
    }
}

inline bool valid_utf8(const std::string& b) {
    for (std::size_t i = 0; i < b.size();) {
        const unsigned char c = static_cast<unsigned char>(b[i]);
        if (c < 0x80) { ++i; continue; }
        std::size_t n = 0;
        std::uint32_t cp = 0;
        if ((c >> 5) == 0x6) { n = 2; cp = c & 0x1Fu; }
        else if ((c >> 4) == 0xE) { n = 3; cp = c & 0x0Fu; }
        else if ((c >> 3) == 0x1E) { n = 4; cp = c & 0x07u; }
        else return false;
        if (i + n > b.size()) return false;
        for (std::size_t k = 1; k < n; ++k) {
            const unsigned char t = static_cast<unsigned char>(b[i + k]);
            if ((t >> 6) != 0x2) return false;
            cp = cp << 6 | (t & 0x3Fu);
        }
        static const std::uint32_t kLowest[5] = {0, 0, 0x80, 0x800, 0x10000};
        if (cp < kLowest[n] || cp > 0x10FFFF || (cp >= 0xD800 && cp <= 0xDFFF)) return false;
        i += n;
    }
    return true;
}

struct Reader {
    std::string_view buf;
    std::size_t pos = 0;
    int depth = 0;

    [[noreturn]] void refuse(const char* word) const { throw Refusal(word, pos); }

    unsigned char at() const {
        return pos < buf.size() ? static_cast<unsigned char>(buf[pos]) : 0;
    }

    bool digit() const { return at() >= '0' && at() <= '9'; }

    void skip_ws() {
        while (pos < buf.size() && ws(static_cast<unsigned char>(buf[pos]))) ++pos;
    }

    void enter() {
        if (++depth > kDepthLimit) refuse("depth_exceeded");
    }

    std::string str() {
        if (at() != '"') refuse("wrong_type");
        ++pos;
        std::string out;
        for (;;) {
            if (pos >= buf.size()) refuse("malformed");
            const unsigned char c = static_cast<unsigned char>(buf[pos]);
            if (c == '"') {
                ++pos;
                if (!valid_utf8(out)) refuse("bad_string");
                return out;
            }
            if (c < 0x20) refuse("bad_string");
            if (c == '\\') {
                escape(out);
            } else {
                out += static_cast<char>(c);
                ++pos;
            }
        }
    }

    void escape(std::string& out) {
        ++pos;
        if (pos >= buf.size()) refuse("malformed");
        const unsigned char c = static_cast<unsigned char>(buf[pos]);
        ++pos;
        switch (c) {
            case '"': case '\\': case '/': out += static_cast<char>(c); return;
            case 'b': out += static_cast<char>(0x08); return;
            case 'f': out += static_cast<char>(0x0c); return;
            case 'n': out += '\n'; return;
            case 'r': out += '\r'; return;
            case 't': out += '\t'; return;
            case 'u': break;
            default: refuse("bad_string");
        }
        std::uint32_t u = hex4();
        if (u >= 0xDC00 && u <= 0xDFFF) refuse("bad_string");
        if (u >= 0xD800 && u <= 0xDBFF) {
            if (pos + 1 >= buf.size() || buf[pos] != '\\' || buf[pos + 1] != 'u') refuse("bad_string");
            pos += 2;
            const std::uint32_t low = hex4();
            if (low < 0xDC00 || low > 0xDFFF) refuse("bad_string");
            u = 0x10000 + ((u - 0xD800) << 10) + (low - 0xDC00);
        }
        append_rune(out, u);
    }

    std::uint32_t hex4() {
        if (pos + 4 > buf.size()) refuse("bad_string");
        std::uint32_t u = 0;
        for (std::size_t i = 0; i < 4; ++i) {
            const unsigned char c = static_cast<unsigned char>(buf[pos + i]);
            if (c >= '0' && c <= '9') u = u << 4 | static_cast<std::uint32_t>(c - '0');
            else if (c >= 'a' && c <= 'f') u = u << 4 | static_cast<std::uint32_t>(c - 'a' + 10);
            else if (c >= 'A' && c <= 'F') u = u << 4 | static_cast<std::uint32_t>(c - 'A' + 10);
            else refuse("bad_string");
        }
        pos += 4;
        return u;
    }

    std::int64_t integer(std::int64_t low, std::int64_t high) {
        const unsigned char c = at();
        if (c != '-' && !digit()) refuse("wrong_type");
        const bool negative = c == '-';
        if (negative) ++pos;
        if (!digit()) refuse("malformed");
        std::uint64_t u = 0;
        if (at() == '0') {
            ++pos;
        } else {
            while (digit()) {
                if (u > 922337203685477580ULL) refuse("number_spelling");
                u = u * 10 + static_cast<std::uint64_t>(at() - '0');
                ++pos;
            }
        }
        const unsigned char after = at();
        if (after == '.' || after == 'e' || after == 'E' || digit()) refuse("number_spelling");
        if (negative && u == 0) refuse("number_spelling");
        std::int64_t n = 0;
        if (negative) {
            if (u > (1ULL << 63)) refuse("number_spelling");
            n = u == (1ULL << 63) ? INT64_MIN : -static_cast<std::int64_t>(u);
        } else {
            if (u > static_cast<std::uint64_t>(INT64_MAX)) refuse("number_spelling");
            n = static_cast<std::int64_t>(u);
        }
        if (n < low || n > high) refuse("number_spelling");
        return n;
    }

    bool boolean() {
        if (at() == 't') { literal("true"); return true; }
        if (at() == 'f') { literal("false"); return false; }
        refuse("wrong_type");
    }

    void literal(std::string_view word) {
        if (buf.substr(pos, word.size()) != word) refuse("malformed");
        pos += word.size();
    }

    std::vector<std::string> str_list() {
        if (at() != '[') refuse("wrong_type");
        enter();
        ++pos;
        std::vector<std::string> out;
        skip_ws();
        if (at() != ']') {
            for (;;) {
                skip_ws();
                out.push_back(str());
                skip_ws();
                if (at() != ',') break;
                ++pos;
            }
        }
        if (at() != ']') refuse("malformed");
        ++pos;
        --depth;
        return out;
    }

    std::map<std::string, Raw> raw_map() {
        if (at() != '{') refuse("wrong_type");
        enter();
        ++pos;
        std::map<std::string, Raw> out;
        skip_ws();
        if (at() != '}') {
            for (;;) {
                skip_ws();
                if (at() != '"') refuse("malformed");
                const std::string k = str();
                if (out.count(k) != 0) refuse("duplicate_key");
                skip_ws();
                if (at() != ':') refuse("malformed");
                ++pos;
                skip_ws();
                out[k] = raw_value();
                skip_ws();
                if (at() != ',') break;
                ++pos;
            }
        }
        if (at() != '}') refuse("malformed");
        ++pos;
        --depth;
        return out;
    }

    Raw raw_value() {
        const std::size_t start = pos;
        skip_value();
        return std::string(buf.substr(start, pos - start));
    }

    void skip_value() {
        const unsigned char c = at();
        if (c == '"') skip_string();
        else if (c == '{' || c == '[') skip_container();
        else if (c == 't') literal("true");
        else if (c == 'f') literal("false");
        else if (c == 'n') literal("null");
        else if (c == '-' || digit()) skip_number();
        else refuse("malformed");
    }

    // An opaque value is validated and carried, never interpreted. Its syntax is
    // the record's own — the same string reader, so an escape, a control byte or
    // a lone surrogate is judged identically at any depth — and what it is free
    // to spell, it keeps: the bytes between these two offsets are what a writer
    // re-emits. A number is walked, never converted, so a value no host type
    // holds survives the reader that carried it.
    void skip_string() { str(); }

    void some_digits() {
        int n = 0;
        while (digit()) { ++pos; ++n; }
        if (n == 0) refuse("number_spelling");
    }

    void skip_number() {
        if (at() == '-') ++pos;
        const unsigned char c = at();
        if (c == '0') ++pos;
        else if (c >= '1' && c <= '9') { while (digit()) ++pos; }
        else refuse("number_spelling");
        if (at() == '.') { ++pos; some_digits(); }
        if (at() == 'e' || at() == 'E') {
            ++pos;
            if (at() == '+' || at() == '-') ++pos;
            some_digits();
        }
    }

    void skip_container() {
        const unsigned char opener = at();
        const char shut = opener == '{' ? '}' : ']';
        enter();
        ++pos;
        skip_ws();
        std::map<std::string, bool> seen;
        if (at() != static_cast<unsigned char>(shut)) {
            for (;;) {
                skip_ws();
                if (opener == '{') {
                    if (at() != '"') refuse("malformed");
                    const std::string k = str();
                    if (!seen.emplace(k, true).second) refuse("duplicate_key");
                    skip_ws();
                    if (at() != ':') refuse("malformed");
                    ++pos;
                    skip_ws();
                }
                skip_value();
                skip_ws();
                if (at() != ',') break;
                ++pos;
            }
        }
        if (at() != static_cast<unsigned char>(shut)) refuse("malformed");
        ++pos;
        --depth;
    }
};

inline RequestIdentity decode_requestidentity(Reader& r);
inline Submission decode_submission(Reader& r);
inline Receipt decode_receipt(Reader& r);
inline AcceptanceResult decode_acceptanceresult(Reader& r);
inline HistoryWindow decode_historywindow(Reader& r);
inline CancellationResult decode_cancellationresult(Reader& r);
inline OARecoverableAcceptanceGetHistoryWindowArguments decode_oarecoverableacceptancegethistorywindowarguments(Reader& r);
inline OARecoverableAcceptanceSubmitArguments decode_oarecoverableacceptancesubmitarguments(Reader& r);
inline OARecoverableAcceptanceReconcileArguments decode_oarecoverableacceptancereconcilearguments(Reader& r);
inline OARecoverableAcceptanceCancelWorkArguments decode_oarecoverableacceptancecancelworkarguments(Reader& r);
inline OAServiceFrame decode_oaserviceframe(Reader& r);
inline OAServiceReply decode_oaservicereply(Reader& r);
inline OAServiceError decode_oaserviceerror(Reader& r);
inline OARecoverableAcceptanceGetHistoryWindowResult decode_oarecoverableacceptancegethistorywindowresult(Reader& r);
inline OARecoverableAcceptanceSubmitResult decode_oarecoverableacceptancesubmitresult(Reader& r);
inline OARecoverableAcceptanceReconcileResult decode_oarecoverableacceptancereconcileresult(Reader& r);
inline OARecoverableAcceptanceCancelWorkResult decode_oarecoverableacceptancecancelworkresult(Reader& r);

inline RequestIdentity decode_requestidentity(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    RequestIdentity v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "key") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.key = r.str();
            } else if (key == "history_epoch") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.history_epoch = r.str();
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 3u) != 3u) r.refuse("missing_field");
    return v;
}

inline Submission decode_submission(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    Submission v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "identity") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.identity = decode_requestidentity(r);
            } else if (key == "kind") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.kind = r.str();
            } else if (key == "spec") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                v.spec = decode_binary(r.str());
            } else if (key == "required_guarantees") {
                if (seen & 8u) r.refuse("duplicate_field");
                seen |= 8u;
                v.required_guarantees = r.str_list();
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 15u) != 15u) r.refuse("missing_field");
    return v;
}

inline Receipt decode_receipt(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    Receipt v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "identity") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.identity = decode_requestidentity(r);
            } else if (key == "logical_owner") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.logical_owner = r.str();
            } else if (key == "operation_id") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                v.operation_id = r.str();
            } else if (key == "accepted_guarantees") {
                if (seen & 8u) r.refuse("duplicate_field");
                seen |= 8u;
                v.accepted_guarantees = r.str_list();
            } else if (key == "history_retention_ms") {
                if (seen & 16u) r.refuse("duplicate_field");
                seen |= 16u;
                v.history_retention_ms = r.integer(INT64_MIN, INT64_MAX);
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 31u) != 31u) r.refuse("missing_field");
    return v;
}

inline AcceptanceResult decode_acceptanceresult(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    AcceptanceResult v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "outcome") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.outcome = r.str();
            } else if (key == "receipt") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.receipt = decode_receipt(r);
            } else if (key == "reason") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                v.reason = r.str();
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 5u) != 5u) r.refuse("missing_field");
    if (v.outcome != "accepted" && v.outcome != "definitely_not_accepted" && v.outcome != "unknown" && v.outcome != "key_conflict" && v.outcome != "forbidden" && v.outcome != "invalid") { r.refuse("bad_enum"); }
    return v;
}

inline HistoryWindow decode_historywindow(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    HistoryWindow v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "logical_owner") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.logical_owner = r.str();
            } else if (key == "history_epoch") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.history_epoch = r.str();
            } else if (key == "minimum_retention_ms") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                v.minimum_retention_ms = r.integer(INT64_MIN, INT64_MAX);
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 7u) != 7u) r.refuse("missing_field");
    return v;
}

inline CancellationResult decode_cancellationresult(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    CancellationResult v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "outcome") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.outcome = r.str();
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 1u) != 1u) r.refuse("missing_field");
    if (v.outcome != "requested" && v.outcome != "already_terminal" && v.outcome != "unknown" && v.outcome != "forbidden" && v.outcome != "unsupported") { r.refuse("bad_enum"); }
    return v;
}

inline OARecoverableAcceptanceGetHistoryWindowArguments decode_oarecoverableacceptancegethistorywindowarguments(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OARecoverableAcceptanceGetHistoryWindowArguments v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (false) {
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    return v;
}

inline OARecoverableAcceptanceSubmitArguments decode_oarecoverableacceptancesubmitarguments(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OARecoverableAcceptanceSubmitArguments v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "submission") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.submission = decode_submission(r);
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 1u) != 1u) r.refuse("missing_field");
    return v;
}

inline OARecoverableAcceptanceReconcileArguments decode_oarecoverableacceptancereconcilearguments(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OARecoverableAcceptanceReconcileArguments v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "identity") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.identity = decode_requestidentity(r);
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 1u) != 1u) r.refuse("missing_field");
    return v;
}

inline OARecoverableAcceptanceCancelWorkArguments decode_oarecoverableacceptancecancelworkarguments(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OARecoverableAcceptanceCancelWorkArguments v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "identity") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.identity = decode_requestidentity(r);
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 1u) != 1u) r.refuse("missing_field");
    return v;
}

inline OAServiceFrame decode_oaserviceframe(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OAServiceFrame v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "version") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.version = static_cast<std::int32_t>(r.integer(INT32_MIN, INT32_MAX));
            } else if (key == "service") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.service = r.str();
            } else if (key == "method") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                v.method = r.str();
            } else if (key == "arguments") {
                if (seen & 8u) r.refuse("duplicate_field");
                seen |= 8u;
                v.arguments = r.raw_value();
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 15u) != 15u) r.refuse("missing_field");
    return v;
}

inline OAServiceReply decode_oaservicereply(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OAServiceReply v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "version") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.version = static_cast<std::int32_t>(r.integer(INT32_MIN, INT32_MAX));
            } else if (key == "service") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.service = r.str();
            } else if (key == "method") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                v.method = r.str();
            } else if (key == "ok") {
                if (seen & 8u) r.refuse("duplicate_field");
                seen |= 8u;
                v.ok = r.boolean();
            } else if (key == "payload") {
                if (seen & 16u) r.refuse("duplicate_field");
                seen |= 16u;
                v.payload = r.raw_value();
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 31u) != 31u) r.refuse("missing_field");
    return v;
}

inline OAServiceError decode_oaserviceerror(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OAServiceError v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "code") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.code = r.str();
            } else if (key == "message") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.message = r.str();
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 3u) != 3u) r.refuse("missing_field");
    return v;
}

inline OARecoverableAcceptanceGetHistoryWindowResult decode_oarecoverableacceptancegethistorywindowresult(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OARecoverableAcceptanceGetHistoryWindowResult v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "value") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.value = decode_historywindow(r);
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 1u) != 1u) r.refuse("missing_field");
    return v;
}

inline OARecoverableAcceptanceSubmitResult decode_oarecoverableacceptancesubmitresult(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OARecoverableAcceptanceSubmitResult v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "value") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.value = decode_acceptanceresult(r);
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 1u) != 1u) r.refuse("missing_field");
    return v;
}

inline OARecoverableAcceptanceReconcileResult decode_oarecoverableacceptancereconcileresult(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OARecoverableAcceptanceReconcileResult v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "value") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.value = decode_acceptanceresult(r);
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 1u) != 1u) r.refuse("missing_field");
    return v;
}

inline OARecoverableAcceptanceCancelWorkResult decode_oarecoverableacceptancecancelworkresult(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OARecoverableAcceptanceCancelWorkResult v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "value") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.value = decode_cancellationresult(r);
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 1u) != 1u) r.refuse("missing_field");
    return v;
}

inline AcceptanceResult decode(std::string_view data) {
    Reader r{data};
    r.skip_ws();
    AcceptanceResult v = decode_acceptanceresult(r);
    r.skip_ws();
    if (r.pos < r.buf.size()) r.refuse("trailing_bytes");
    return v;
}

// kRefusals is in the order two of them are chosen between.
inline const std::vector<std::string> kRefusals = {"malformed", "bad_string", "number_spelling", "wrong_type", "depth_exceeded", "duplicate_key", "duplicate_field", "unknown_field", "missing_field", "bad_binary", "bad_enum", "trailing_bytes"};

inline int refusal_rank(std::string_view word) {
    for (std::size_t i = 0; i < kRefusals.size(); ++i)
        if (kRefusals[i] == word) return static_cast<int>(i);
    return -1;
}

inline std::string encode_binary(const std::vector<std::uint8_t>& value){
 const char* alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
 std::string out;
 for(std::size_t i=0;i<value.size();i+=3){auto n=value.size()-i;std::uint32_t v=std::uint32_t(value[i])<<16;if(n>1)v|=std::uint32_t(value[i+1])<<8;if(n>2)v|=value[i+2];out+=alphabet[v>>18];out+=alphabet[(v>>12)&63];out+=n>1?alphabet[(v>>6)&63]:'=';out+=n>2?alphabet[v&63]:'=';}
 return out;
}
inline std::vector<std::uint8_t> decode_binary(const std::string& text){
 auto refuse=[](const char* word){throw Refusal(word,0);};
 const std::string alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
 if(text.size()%4)refuse("bad_binary");
 std::vector<std::uint8_t> out;
 for(std::size_t i=0;i<text.size();i+=4){std::uint32_t v=0;int pad=0;
  for(int j=0;j<4;j++){auto c=text[i+j];std::size_t digit=0;
   if(c=='='){if(j<2||i+4!=text.size())refuse("bad_binary");pad++;}
   else{if(pad)refuse("bad_binary");digit=alphabet.find(c);if(digit==std::string::npos)refuse("bad_binary");}
   v=(v<<6)|static_cast<std::uint32_t>(digit);
  }
  out.push_back(static_cast<std::uint8_t>(v>>16));if(pad<2)out.push_back(static_cast<std::uint8_t>(v>>8));if(!pad)out.push_back(static_cast<std::uint8_t>(v));
 }
 if(encode_binary(out)!=text)refuse("bad_binary");return out;
}

struct FrameWriter{virtual ~FrameWriter()=default;virtual void WriteFrame(std::string_view)=0;};
struct DispatchError:std::runtime_error{using std::runtime_error::runtime_error;};
inline OAServiceFrame service_payload(std::string_view frame){Reader r{frame};r.skip_ws();auto v=decode_oaserviceframe(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");if(v.version!=1)throw DispatchError("unknown_version");return v;}

struct FrameExchanger{virtual ~FrameExchanger()=default;virtual std::string ExchangeFrame(std::string_view)=0;};
struct ServiceError:std::runtime_error{std::string code,message;ServiceError(std::string c,std::string m):std::runtime_error(m.empty()?c:m),code(c),message(m){}};
inline Raw service_response(std::string_view frame,std::string_view service,std::string_view method){
 Reader r{frame};r.skip_ws();auto v=decode_oaservicereply(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");if(v.version!=1)throw DispatchError("unknown_version");if(v.service!=service||v.method!=method)throw DispatchError("mismatched_response");
 if(!v.ok){Reader e{v.payload};e.depth=1;e.skip_ws();auto error=decode_oaserviceerror(e);e.skip_ws();if(e.pos!=e.buf.size())e.refuse("trailing_bytes");if(error.code.empty())throw DispatchError("invalid_error");throw ServiceError(error.code,error.message);}return v.payload;
}
inline std::string service_reply(const OAServiceFrame& request,const Raw& payload,const ServiceError* error=nullptr){
 OAServiceReply reply;reply.version=1;reply.service=request.service;reply.method=request.method;reply.ok=error==nullptr;reply.payload=payload;
 if(error){OAServiceError e;e.code=error->code.empty()?"handler_error":error->code;e.message=error->message;reply.payload.clear();enc_oaserviceerror(reply.payload,e,1);}
 std::string frame;enc_oaservicereply(frame,reply,0);Reader r{frame};r.skip_ws();decode_oaservicereply(r);return frame;
}
struct RecoverableAcceptance{virtual ~RecoverableAcceptance()=default;
virtual HistoryWindow GetHistoryWindow()=0;
virtual AcceptanceResult Submit(const Submission& arg0)=0;
virtual AcceptanceResult Reconcile(const RequestIdentity& arg0)=0;
virtual CancellationResult CancelWork(const RequestIdentity& arg0)=0;
};
template<class Transport>struct RecoverableAcceptanceClient:RecoverableAcceptance{Transport& transport_;explicit RecoverableAcceptanceClient(Transport&t):transport_(t){}
HistoryWindow GetHistoryWindow()override{OARecoverableAcceptanceGetHistoryWindowArguments args;
OAServiceFrame v;v.version=1;v.service="abstraction.job/acceptance@1";v.method="GetHistoryWindow";enc_oarecoverableacceptancegethistorywindowarguments(v.arguments,args,1);std::string frame;enc_oaserviceframe(frame,v,0);service_payload(frame);
auto response=transport_.ExchangeFrame(frame);auto payload=service_response(response,v.service,v.method);Reader r{payload};r.depth=1;r.skip_ws();auto result=decode_oarecoverableacceptancegethistorywindowresult(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");
return result.value;
}
AcceptanceResult Submit(const Submission& arg0)override{OARecoverableAcceptanceSubmitArguments args;
args.submission=arg0;
OAServiceFrame v;v.version=1;v.service="abstraction.job/acceptance@1";v.method="Submit";enc_oarecoverableacceptancesubmitarguments(v.arguments,args,1);std::string frame;enc_oaserviceframe(frame,v,0);service_payload(frame);
auto response=transport_.ExchangeFrame(frame);auto payload=service_response(response,v.service,v.method);Reader r{payload};r.depth=1;r.skip_ws();auto result=decode_oarecoverableacceptancesubmitresult(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");
return result.value;
}
AcceptanceResult Reconcile(const RequestIdentity& arg0)override{OARecoverableAcceptanceReconcileArguments args;
args.identity=arg0;
OAServiceFrame v;v.version=1;v.service="abstraction.job/acceptance@1";v.method="Reconcile";enc_oarecoverableacceptancereconcilearguments(v.arguments,args,1);std::string frame;enc_oaserviceframe(frame,v,0);service_payload(frame);
auto response=transport_.ExchangeFrame(frame);auto payload=service_response(response,v.service,v.method);Reader r{payload};r.depth=1;r.skip_ws();auto result=decode_oarecoverableacceptancereconcileresult(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");
return result.value;
}
CancellationResult CancelWork(const RequestIdentity& arg0)override{OARecoverableAcceptanceCancelWorkArguments args;
args.identity=arg0;
OAServiceFrame v;v.version=1;v.service="abstraction.job/acceptance@1";v.method="CancelWork";enc_oarecoverableacceptancecancelworkarguments(v.arguments,args,1);std::string frame;enc_oaserviceframe(frame,v,0);service_payload(frame);
auto response=transport_.ExchangeFrame(frame);auto payload=service_response(response,v.service,v.method);Reader r{payload};r.depth=1;r.skip_ws();auto result=decode_oarecoverableacceptancecancelworkresult(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");
return result.value;
}
};
struct RecoverableAcceptanceDispatcher:FrameWriter,FrameExchanger{RecoverableAcceptance&handler;explicit RecoverableAcceptanceDispatcher(RecoverableAcceptance&h):handler(h){}
void WriteFrame(std::string_view frame)override{auto v=service_payload(frame);if(v.service!="abstraction.job/acceptance@1")throw DispatchError("unknown_service");
if(v.method=="GetHistoryWindow"){
throw DispatchError("wrong_mode");}
if(v.method=="Submit"){
throw DispatchError("wrong_mode");}
if(v.method=="Reconcile"){
throw DispatchError("wrong_mode");}
if(v.method=="CancelWork"){
throw DispatchError("wrong_mode");}
throw DispatchError("unknown_method");}
std::string ExchangeFrame(std::string_view frame)override{auto v=service_payload(frame);if(v.service!="abstraction.job/acceptance@1"){ServiceError e("unknown_service","");return service_reply(v,"",&e);}
try{
if(v.method=="GetHistoryWindow"){
Reader r{v.arguments};r.depth=1;r.skip_ws();auto args=decode_oarecoverableacceptancegethistorywindowarguments(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");auto payload=invoke_GetHistoryWindow(args);return service_reply(v,payload);}
if(v.method=="Submit"){
Reader r{v.arguments};r.depth=1;r.skip_ws();auto args=decode_oarecoverableacceptancesubmitarguments(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");auto payload=invoke_Submit(args);return service_reply(v,payload);}
if(v.method=="Reconcile"){
Reader r{v.arguments};r.depth=1;r.skip_ws();auto args=decode_oarecoverableacceptancereconcilearguments(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");auto payload=invoke_Reconcile(args);return service_reply(v,payload);}
if(v.method=="CancelWork"){
Reader r{v.arguments};r.depth=1;r.skip_ws();auto args=decode_oarecoverableacceptancecancelworkarguments(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");auto payload=invoke_CancelWork(args);return service_reply(v,payload);}
throw ServiceError("unknown_method","");}catch(const ServiceError&e){return service_reply(v,"",&e);}catch(const Refusal&e){ServiceError error(e.word,"");return service_reply(v,"",&error);}
}
Raw invoke_GetHistoryWindow(const OARecoverableAcceptanceGetHistoryWindowArguments&args){
HistoryWindow result{};
try{
result=handler.GetHistoryWindow();
}catch(const ServiceError&){throw;}catch(...){throw ServiceError("handler_error","handler failed");}
try{
OARecoverableAcceptanceGetHistoryWindowResult value;
value.value=result;
Raw payload;enc_oarecoverableacceptancegethistorywindowresult(payload,value,1);Reader r{payload};r.depth=1;r.skip_ws();decode_oarecoverableacceptancegethistorywindowresult(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");return payload;
}catch(...){throw ServiceError("invalid_result","");}
}
Raw invoke_Submit(const OARecoverableAcceptanceSubmitArguments&args){
AcceptanceResult result{};
try{
result=handler.Submit(args.submission);
}catch(const ServiceError&){throw;}catch(...){throw ServiceError("handler_error","handler failed");}
try{
OARecoverableAcceptanceSubmitResult value;
value.value=result;
Raw payload;enc_oarecoverableacceptancesubmitresult(payload,value,1);Reader r{payload};r.depth=1;r.skip_ws();decode_oarecoverableacceptancesubmitresult(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");return payload;
}catch(...){throw ServiceError("invalid_result","");}
}
Raw invoke_Reconcile(const OARecoverableAcceptanceReconcileArguments&args){
AcceptanceResult result{};
try{
result=handler.Reconcile(args.identity);
}catch(const ServiceError&){throw;}catch(...){throw ServiceError("handler_error","handler failed");}
try{
OARecoverableAcceptanceReconcileResult value;
value.value=result;
Raw payload;enc_oarecoverableacceptancereconcileresult(payload,value,1);Reader r{payload};r.depth=1;r.skip_ws();decode_oarecoverableacceptancereconcileresult(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");return payload;
}catch(...){throw ServiceError("invalid_result","");}
}
Raw invoke_CancelWork(const OARecoverableAcceptanceCancelWorkArguments&args){
CancellationResult result{};
try{
result=handler.CancelWork(args.identity);
}catch(const ServiceError&){throw;}catch(...){throw ServiceError("handler_error","handler failed");}
try{
OARecoverableAcceptanceCancelWorkResult value;
value.value=result;
Raw payload;enc_oarecoverableacceptancecancelworkresult(payload,value,1);Reader r{payload};r.depth=1;r.skip_ws();decode_oarecoverableacceptancecancelworkresult(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");return payload;
}catch(...){throw ServiceError("invalid_result","");}
}
};

}  // namespace abstraction::job::acceptance
