# Code generated by abstraction-idl from abstraction-job/acceptance.thrift. DO NOT EDIT.

_HEX = b"0123456789abcdef"
_WS = (0x20, 0x09, 0x0A, 0x0D)
_SHORT = {0x22: b'\\"', 0x5C: b"\\\\", 0x08: b"\\b", 0x0C: b"\\f",
          0x0A: b"\\n", 0x0D: b"\\r", 0x09: b"\\t"}


def esc_byte(out, c):
    short = _SHORT.get(c)
    if short is not None:
        out += short
    elif c < 0x20:
        out += b"\\u00" + bytes([_HEX[c >> 4], _HEX[c & 0xF]])
    else:
        out.append(c)


def num(out, n):
    out += str(int(n)).encode("ascii")


def pad(out, depth):
    out += b" " * (depth * 2)


def strs(out, v, depth):
    if not v:
        out += b"[]"
        return
    out += b"[\n"
    for i, s in enumerate(v):
        pad(out, depth + 1)
        esc(out, s)
        if i + 1 < len(v):
            out += b","
        out += b"\n"
    pad(out, depth)
    out += b"]"


def raw(out, s, depth):
    b = s.encode("utf-8") if isinstance(s, str) else s
    i, n = 0, len(b)
    while i < n:
        c = b[i]
        if c in _WS:
            i += 1
        elif c == 0x22:
            j = i + 1
            while j < n:
                if b[j] == 0x5C:
                    j += 2
                    continue
                if b[j] == 0x22:
                    j += 1
                    break
                j += 1
            out += b[i:j]
            i = j
        elif c in (0x7B, 0x5B):
            out.append(c)
            i += 1
            j = i
            while j < n and b[j] in _WS:
                j += 1
            if j < n and b[j] in (0x7D, 0x5D):
                out.append(b[j])
                i = j + 1
            else:
                depth += 1
                out += b"\n"
                pad(out, depth)
        elif c in (0x7D, 0x5D):
            depth -= 1
            out += b"\n"
            pad(out, depth)
            out.append(c)
            i += 1
        elif c == 0x2C:
            out += b",\n"
            pad(out, depth)
            i += 1
        elif c == 0x3A:
            out += b": "
            i += 1
        else:
            out.append(c)
            i += 1


def rawmap(out, m, depth):
    keys = sorted(m, key=lambda k: k.encode("utf-8"))
    if not keys:
        out += b"{}"
        return
    out += b"{\n"
    for i, k in enumerate(keys):
        pad(out, depth + 1)
        esc(out, k)
        out += b": "
        raw(out, m[k], depth + 1)
        if i + 1 < len(keys):
            out += b","
        out += b"\n"
    pad(out, depth)
    out += b"}"

def esc(out, s):
    out += b'"'
    for c in s.encode("utf-8"):
        esc_byte(out, c)
    out += b'"'


OUTCOME_NAMES = ["accepted", "definitely_not_accepted", "unknown", "key_conflict", "forbidden", "invalid"]
OUTCOME_UNKNOWN = "refuse"


CANCELLATIONOUTCOME_NAMES = ["requested", "already_terminal", "unknown", "forbidden", "unsupported"]
CANCELLATIONOUTCOME_UNKNOWN = "refuse"


class RequestIdentity:
    def __init__(self, **kw):
        self.key = kw.get("key", "")
        self.history_epoch = kw.get("history_epoch", "")


class Submission:
    def __init__(self, **kw):
        self.identity = kw.get("identity", RequestIdentity())
        self.kind = kw.get("kind", "")
        self.spec = kw.get("spec", b"")
        self.required_guarantees = kw.get("required_guarantees", [])


class Receipt:
    def __init__(self, **kw):
        self.identity = kw.get("identity", RequestIdentity())
        self.logical_owner = kw.get("logical_owner", "")
        self.operation_id = kw.get("operation_id", "")
        self.accepted_guarantees = kw.get("accepted_guarantees", [])
        self.history_retention_ms = kw.get("history_retention_ms", 0)


class AcceptanceResult:
    def __init__(self, **kw):
        self.outcome = kw.get("outcome", "")
        self.receipt = kw.get("receipt", None)
        self.reason = kw.get("reason", "")


class HistoryWindow:
    def __init__(self, **kw):
        self.logical_owner = kw.get("logical_owner", "")
        self.history_epoch = kw.get("history_epoch", "")
        self.minimum_retention_ms = kw.get("minimum_retention_ms", 0)


class CancellationResult:
    def __init__(self, **kw):
        self.outcome = kw.get("outcome", "")


class OARecoverableAcceptanceGetHistoryWindowArguments:
    def __init__(self, **kw):
        pass


class OARecoverableAcceptanceSubmitArguments:
    def __init__(self, **kw):
        self.submission = kw.get("submission", Submission())


class OARecoverableAcceptanceReconcileArguments:
    def __init__(self, **kw):
        self.identity = kw.get("identity", RequestIdentity())


class OARecoverableAcceptanceCancelWorkArguments:
    def __init__(self, **kw):
        self.identity = kw.get("identity", RequestIdentity())


class OAServiceFrame:
    def __init__(self, **kw):
        self.version = kw.get("version", 0)
        self.service = kw.get("service", "")
        self.method = kw.get("method", "")
        self.arguments = kw.get("arguments", "")


class OAServiceReply:
    def __init__(self, **kw):
        self.version = kw.get("version", 0)
        self.service = kw.get("service", "")
        self.method = kw.get("method", "")
        self.ok = kw.get("ok", False)
        self.payload = kw.get("payload", "")


class OAServiceError:
    def __init__(self, **kw):
        self.code = kw.get("code", "")
        self.message = kw.get("message", "")


class OARecoverableAcceptanceGetHistoryWindowResult:
    def __init__(self, **kw):
        self.value = kw.get("value", HistoryWindow())


class OARecoverableAcceptanceSubmitResult:
    def __init__(self, **kw):
        self.value = kw.get("value", AcceptanceResult())


class OARecoverableAcceptanceReconcileResult:
    def __init__(self, **kw):
        self.value = kw.get("value", AcceptanceResult())


class OARecoverableAcceptanceCancelWorkResult:
    def __init__(self, **kw):
        self.value = kw.get("value", CancellationResult())


def enc_requestidentity(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "key")
    out += b": "
    esc(out, v.key)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "history_epoch")
    out += b": "
    esc(out, v.history_epoch)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_submission(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "identity")
    out += b": "
    enc_requestidentity(out, v.identity, depth + 1)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "kind")
    out += b": "
    esc(out, v.kind)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "spec")
    out += b": "
    esc(out, _encode_binary(v.spec))
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "required_guarantees")
    out += b": "
    strs(out, v.required_guarantees, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_receipt(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "identity")
    out += b": "
    enc_requestidentity(out, v.identity, depth + 1)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "logical_owner")
    out += b": "
    esc(out, v.logical_owner)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "operation_id")
    out += b": "
    esc(out, v.operation_id)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "accepted_guarantees")
    out += b": "
    strs(out, v.accepted_guarantees, depth + 1)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "history_retention_ms")
    out += b": "
    num(out, v.history_retention_ms)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_acceptanceresult(out, v, depth):
    if type(v.outcome) is not str: raise Refusal("wrong_type",0)
    if v.outcome != "accepted" and v.outcome != "definitely_not_accepted" and v.outcome != "unknown" and v.outcome != "key_conflict" and v.outcome != "forbidden" and v.outcome != "invalid": raise Refusal("bad_enum",0)
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "outcome")
    out += b": "
    esc(out, v.outcome)
    if v.receipt is not None:
        out += b","
        out += b"\n"
        pad(out, depth + 1)
        esc(out, "receipt")
        out += b": "
        enc_receipt(out, v.receipt, depth + 1)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "reason")
    out += b": "
    esc(out, v.reason)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_historywindow(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "logical_owner")
    out += b": "
    esc(out, v.logical_owner)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "history_epoch")
    out += b": "
    esc(out, v.history_epoch)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "minimum_retention_ms")
    out += b": "
    num(out, v.minimum_retention_ms)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_cancellationresult(out, v, depth):
    if type(v.outcome) is not str: raise Refusal("wrong_type",0)
    if v.outcome != "requested" and v.outcome != "already_terminal" and v.outcome != "unknown" and v.outcome != "forbidden" and v.outcome != "unsupported": raise Refusal("bad_enum",0)
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "outcome")
    out += b": "
    esc(out, v.outcome)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oarecoverableacceptancegethistorywindowarguments(out, v, depth):
    out += b"{"
    out += b"}"


def enc_oarecoverableacceptancesubmitarguments(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "submission")
    out += b": "
    enc_submission(out, v.submission, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oarecoverableacceptancereconcilearguments(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "identity")
    out += b": "
    enc_requestidentity(out, v.identity, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oarecoverableacceptancecancelworkarguments(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "identity")
    out += b": "
    enc_requestidentity(out, v.identity, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oaserviceframe(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "version")
    out += b": "
    num(out, v.version)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "service")
    out += b": "
    esc(out, v.service)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "method")
    out += b": "
    esc(out, v.method)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "arguments")
    out += b": "
    out += v.arguments.encode("utf-8") if isinstance(v.arguments, str) else v.arguments
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oaservicereply(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "version")
    out += b": "
    num(out, v.version)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "service")
    out += b": "
    esc(out, v.service)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "method")
    out += b": "
    esc(out, v.method)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "ok")
    out += b": "
    out += b"true" if v.ok else b"false"
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "payload")
    out += b": "
    out += v.payload.encode("utf-8") if isinstance(v.payload, str) else v.payload
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oaserviceerror(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "code")
    out += b": "
    esc(out, v.code)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "message")
    out += b": "
    esc(out, v.message)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oarecoverableacceptancegethistorywindowresult(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "value")
    out += b": "
    enc_historywindow(out, v.value, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oarecoverableacceptancesubmitresult(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "value")
    out += b": "
    enc_acceptanceresult(out, v.value, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oarecoverableacceptancereconcileresult(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "value")
    out += b": "
    enc_acceptanceresult(out, v.value, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oarecoverableacceptancecancelworkresult(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "value")
    out += b": "
    enc_cancellationresult(out, v.value, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def encode(v):
    out = bytearray()
    enc_acceptanceresult(out, v, 0)
    out += b"\n"
    return bytes(out)


_QUOTE, _BACKSLASH, _COLON, _COMMA = 0x22, 0x5C, 0x3A, 0x2C
_LBRACE, _RBRACE, _LBRACK, _RBRACK = 0x7B, 0x7D, 0x5B, 0x5D
_MINUS, _ZERO, _NINE, _DOT, _LOWER_U, _LOWER_N = 0x2D, 0x30, 0x39, 0x2E, 0x75, 0x6E
_UNESCAPE = {0x22: 0x22, 0x5C: 0x5C, 0x2F: 0x2F, 0x62: 0x08,
             0x66: 0x0C, 0x6E: 0x0A, 0x72: 0x0D, 0x74: 0x09}
_DEPTH_LIMIT = 64
_I64_DIGITS = 19


class Refusal(ValueError):
    def __init__(self, word, offset):
        super().__init__("refused: %s at byte %d" % (word, offset))
        self.word = word
        self.offset = offset


class _Reader:
    __slots__ = ("buf", "pos", "depth")

    def __init__(self, buf):
        self.buf = buf
        self.pos = 0
        self.depth = 0

    def refuse(self, word):
        return Refusal(word, self.pos)

    def at(self):
        return self.buf[self.pos] if self.pos < len(self.buf) else 0

    def ws(self):
        while self.pos < len(self.buf) and self.buf[self.pos] in _WS:
            self.pos += 1

    def enter(self):
        self.depth += 1
        if self.depth > _DEPTH_LIMIT:
            raise self.refuse("depth_exceeded")

    def digit(self):
        return _ZERO <= self.at() <= _NINE

    def string(self):
        if self.at() != _QUOTE:
            raise self.refuse("wrong_type")
        self.pos += 1
        out = bytearray()
        while True:
            if self.pos >= len(self.buf):
                raise self.refuse("malformed")
            c = self.buf[self.pos]
            if c == _QUOTE:
                self.pos += 1
                try:
                    return out.decode("utf-8")
                except UnicodeDecodeError:
                    raise self.refuse("bad_string") from None
            if c < 0x20:
                raise self.refuse("bad_string")
            if c == _BACKSLASH:
                self.escape(out)
            else:
                out.append(c)
                self.pos += 1

    def escape(self, out):
        self.pos += 1
        if self.pos >= len(self.buf):
            raise self.refuse("malformed")
        c = self.buf[self.pos]
        self.pos += 1
        plain = _UNESCAPE.get(c)
        if plain is not None:
            out.append(plain)
            return
        if c != _LOWER_U:
            raise self.refuse("bad_string")
        u = self.hex4()
        if 0xDC00 <= u <= 0xDFFF:
            raise self.refuse("bad_string")
        if 0xD800 <= u <= 0xDBFF:
            if (self.pos + 1 >= len(self.buf) or self.buf[self.pos] != _BACKSLASH
                    or self.buf[self.pos + 1] != _LOWER_U):
                raise self.refuse("bad_string")
            self.pos += 2
            low = self.hex4()
            if not 0xDC00 <= low <= 0xDFFF:
                raise self.refuse("bad_string")
            u = 0x10000 + ((u - 0xD800) << 10) + (low - 0xDC00)
        out += chr(u).encode("utf-8")

    def hex4(self):
        if self.pos + 4 > len(self.buf):
            raise self.refuse("bad_string")
        u = 0
        for i in range(4):
            c = self.buf[self.pos + i]
            if _ZERO <= c <= _NINE:
                u = u << 4 | (c - _ZERO)
            elif 0x61 <= c <= 0x66:
                u = u << 4 | (c - 0x61 + 10)
            elif 0x41 <= c <= 0x46:
                u = u << 4 | (c - 0x41 + 10)
            else:
                raise self.refuse("bad_string")
        self.pos += 4
        return u

    def integer(self, low, high):
        c = self.at()
        if c != _MINUS and not _ZERO <= c <= _NINE:
            raise self.refuse("wrong_type")
        negative = c == _MINUS
        if negative:
            self.pos += 1
        if not self.digit():
            raise self.refuse("malformed")
        start = self.pos
        if self.at() == _ZERO:
            self.pos += 1
        else:
            while self.digit():
                self.pos += 1
        if self.at() in (_DOT, 0x65, 0x45) or self.digit():
            raise self.refuse("number_spelling")
        if self.pos - start > _I64_DIGITS:
            raise self.refuse("number_spelling")
        n = int(self.buf[start:self.pos])
        if negative:
            if n == 0:
                raise self.refuse("number_spelling")
            n = -n
        if n < low or n > high:
            raise self.refuse("number_spelling")
        return n

    def boolean(self):
        if self.at() == 0x74:
            self.literal(b"true")
            return True
        if self.at() == 0x66:
            self.literal(b"false")
            return False
        raise self.refuse("wrong_type")

    def literal(self, word):
        if self.buf[self.pos:self.pos + len(word)] != word:
            raise self.refuse("malformed")
        self.pos += len(word)

    def str_list(self):
        if self.at() != _LBRACK:
            raise self.refuse("wrong_type")
        self.enter()
        self.pos += 1
        out = []
        self.ws()
        if self.at() != _RBRACK:
            while True:
                self.ws()
                out.append(self.string())
                self.ws()
                if self.at() != _COMMA:
                    break
                self.pos += 1
        if self.at() != _RBRACK:
            raise self.refuse("malformed")
        self.pos += 1
        self.depth -= 1
        return out

    def raw_map(self):
        if self.at() != _LBRACE:
            raise self.refuse("wrong_type")
        self.enter()
        self.pos += 1
        out = {}
        self.ws()
        if self.at() != _RBRACE:
            while True:
                self.ws()
                if self.at() != _QUOTE:
                    raise self.refuse("malformed")
                k = self.string()
                if k in out:
                    raise self.refuse("duplicate_key")
                self.ws()
                if self.at() != _COLON:
                    raise self.refuse("malformed")
                self.pos += 1
                self.ws()
                out[k] = self.raw_value()
                self.ws()
                if self.at() != _COMMA:
                    break
                self.pos += 1
        if self.at() != _RBRACE:
            raise self.refuse("malformed")
        self.pos += 1
        self.depth -= 1
        return out

    def raw_value(self):
        start = self.pos
        self.skip_value()
        return self.buf[start:self.pos]

    def skip_value(self):
        c = self.at()
        if c == _QUOTE:
            self.skip_string()
        elif c in (_LBRACE, _LBRACK):
            self.skip_container()
        elif c == 0x74:
            self.literal(b"true")
        elif c == 0x66:
            self.literal(b"false")
        elif c == 0x6E:
            self.literal(b"null")
        elif c == _MINUS or _ZERO <= c <= _NINE:
            self.skip_number()
        else:
            raise self.refuse("malformed")

    # An opaque value is validated and carried, never interpreted. Its syntax is
    # the record's own — the same string reader, so an escape, a control byte or
    # a lone surrogate is judged identically at any depth — and what it is free
    # to spell, it keeps: the bytes between these two offsets are what a writer
    # re-emits. A number is walked, never converted, so a value no host type
    # holds survives the reader that carried it.
    def skip_string(self):
        self.string()

    def some_digits(self):
        n = 0
        while _ZERO <= self.at() <= _NINE:
            self.pos += 1
            n += 1
        if n == 0:
            raise self.refuse("number_spelling")

    def skip_number(self):
        if self.at() == _MINUS:
            self.pos += 1
        c = self.at()
        if c == _ZERO:
            self.pos += 1
        elif _ZERO < c <= _NINE:
            while _ZERO <= self.at() <= _NINE:
                self.pos += 1
        else:
            raise self.refuse("number_spelling")
        if self.at() == _DOT:
            self.pos += 1
            self.some_digits()
        if self.at() in (0x65, 0x45):
            self.pos += 1
            if self.at() in (0x2B, _MINUS):
                self.pos += 1
            self.some_digits()

    def skip_container(self):
        opener = self.at()
        shut = _RBRACE if opener == _LBRACE else _RBRACK
        self.enter()
        self.pos += 1
        self.ws()
        seen = set()
        if self.at() != shut:
            while True:
                self.ws()
                if opener == _LBRACE:
                    if self.at() != _QUOTE:
                        raise self.refuse("malformed")
                    k = self.string()
                    if k in seen:
                        raise self.refuse("duplicate_key")
                    seen.add(k)
                    self.ws()
                    if self.at() != _COLON:
                        raise self.refuse("malformed")
                    self.pos += 1
                    self.ws()
                self.skip_value()
                self.ws()
                if self.at() != _COMMA:
                    break
                self.pos += 1
        if self.at() != shut:
            raise self.refuse("malformed")
        self.pos += 1
        self.depth -= 1


def _decode_requestidentity(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = RequestIdentity()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "key":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.key = r.string()
            elif key == "history_epoch":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.history_epoch = r.string()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 3 != 3:
        raise r.refuse("missing_field")
    return v


def _decode_submission(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = Submission()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "identity":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.identity = _decode_requestidentity(r)
            elif key == "kind":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.kind = r.string()
            elif key == "spec":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.spec = _decode_binary(r.string())
            elif key == "required_guarantees":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.required_guarantees = r.str_list()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 15 != 15:
        raise r.refuse("missing_field")
    return v


def _decode_receipt(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = Receipt()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "identity":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.identity = _decode_requestidentity(r)
            elif key == "logical_owner":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.logical_owner = r.string()
            elif key == "operation_id":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.operation_id = r.string()
            elif key == "accepted_guarantees":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.accepted_guarantees = r.str_list()
            elif key == "history_retention_ms":
                if seen & 16:
                    raise r.refuse("duplicate_field")
                seen |= 16
                v.history_retention_ms = r.integer(-9223372036854775808, 9223372036854775807)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 31 != 31:
        raise r.refuse("missing_field")
    return v


def _decode_acceptanceresult(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = AcceptanceResult()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "outcome":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.outcome = r.string()
            elif key == "receipt":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.receipt = _decode_receipt(r)
            elif key == "reason":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.reason = r.string()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 5 != 5:
        raise r.refuse("missing_field")
    if v.outcome != "accepted" and v.outcome != "definitely_not_accepted" and v.outcome != "unknown" and v.outcome != "key_conflict" and v.outcome != "forbidden" and v.outcome != "invalid": raise r.refuse("bad_enum")
    return v


def _decode_historywindow(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = HistoryWindow()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "logical_owner":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.logical_owner = r.string()
            elif key == "history_epoch":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.history_epoch = r.string()
            elif key == "minimum_retention_ms":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.minimum_retention_ms = r.integer(-9223372036854775808, 9223372036854775807)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 7 != 7:
        raise r.refuse("missing_field")
    return v


def _decode_cancellationresult(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = CancellationResult()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "outcome":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.outcome = r.string()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    if v.outcome != "requested" and v.outcome != "already_terminal" and v.outcome != "unknown" and v.outcome != "forbidden" and v.outcome != "unsupported": raise r.refuse("bad_enum")
    return v


def _decode_oarecoverableacceptancegethistorywindowarguments(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OARecoverableAcceptanceGetHistoryWindowArguments()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if False:
                pass
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    return v


def _decode_oarecoverableacceptancesubmitarguments(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OARecoverableAcceptanceSubmitArguments()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "submission":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.submission = _decode_submission(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _decode_oarecoverableacceptancereconcilearguments(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OARecoverableAcceptanceReconcileArguments()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "identity":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.identity = _decode_requestidentity(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _decode_oarecoverableacceptancecancelworkarguments(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OARecoverableAcceptanceCancelWorkArguments()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "identity":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.identity = _decode_requestidentity(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _decode_oaserviceframe(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OAServiceFrame()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "version":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.version = r.integer(-2147483648, 2147483647)
            elif key == "service":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.service = r.string()
            elif key == "method":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.method = r.string()
            elif key == "arguments":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.arguments = r.raw_value()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 15 != 15:
        raise r.refuse("missing_field")
    return v


def _decode_oaservicereply(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OAServiceReply()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "version":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.version = r.integer(-2147483648, 2147483647)
            elif key == "service":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.service = r.string()
            elif key == "method":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.method = r.string()
            elif key == "ok":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.ok = r.boolean()
            elif key == "payload":
                if seen & 16:
                    raise r.refuse("duplicate_field")
                seen |= 16
                v.payload = r.raw_value()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 31 != 31:
        raise r.refuse("missing_field")
    return v


def _decode_oaserviceerror(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OAServiceError()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "code":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.code = r.string()
            elif key == "message":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.message = r.string()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 3 != 3:
        raise r.refuse("missing_field")
    return v


def _decode_oarecoverableacceptancegethistorywindowresult(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OARecoverableAcceptanceGetHistoryWindowResult()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "value":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.value = _decode_historywindow(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _decode_oarecoverableacceptancesubmitresult(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OARecoverableAcceptanceSubmitResult()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "value":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.value = _decode_acceptanceresult(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _decode_oarecoverableacceptancereconcileresult(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OARecoverableAcceptanceReconcileResult()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "value":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.value = _decode_acceptanceresult(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _decode_oarecoverableacceptancecancelworkresult(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OARecoverableAcceptanceCancelWorkResult()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "value":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.value = _decode_cancellationresult(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def decode(data):
    r = _Reader(bytes(data))
    r.ws()
    v = _decode_acceptanceresult(r)
    r.ws()
    if r.pos < len(r.buf):
        raise r.refuse("trailing_bytes")
    return v


# REFUSALS is in the order two of them are chosen between.

REFUSALS = ["malformed", "bad_string", "number_spelling", "wrong_type", "depth_exceeded", "duplicate_key", "duplicate_field", "unknown_field", "missing_field", "bad_binary", "bad_enum", "trailing_bytes"]


def refusal_rank(word):
    return REFUSALS.index(word) if word in REFUSALS else -1

def _encode_binary(value):
    if type(value) is not bytes:
        raise Refusal("wrong_type", 0)
    alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
    out = []
    for i in range(0, len(value), 3):
        chunk = value[i:i+3]
        v = int.from_bytes(chunk, "big") << (8 * (3-len(chunk)))
        out.extend((alphabet[v >> 18], alphabet[(v >> 12) & 63], alphabet[(v >> 6) & 63] if len(chunk)>1 else "=", alphabet[v & 63] if len(chunk)>2 else "="))
    return "".join(out)

def _decode_binary(text):
    alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
    def bad():
        raise _Reader(b"").refuse("bad_binary")
    if len(text) % 4: bad()
    out = bytearray()
    for i in range(0,len(text),4):
        v, pad = 0, 0
        for j,c in enumerate(text[i:i+4]):
            if c == "=":
                if j<2 or i+4 != len(text): bad()
                pad += 1
                digit = 0
            else:
                if pad: bad()
                digit = alphabet.find(c)
                if digit < 0: bad()
            v = (v << 6) | digit
        out.append(v >> 16)
        if pad < 2: out.append((v >> 8) & 255)
        if pad == 0: out.append(v & 255)
    result = bytes(out)
    if _encode_binary(result) != text: bad()
    return result


class DispatchError(ValueError):
    def __init__(self, code):
        super().__init__(code)
        self.code = code


def _service_decode(decoder, frame, depth=0):
    if not isinstance(frame, (bytes, bytearray, memoryview)):
        raise TypeError("transport frame must be bytes")
    r = _Reader(bytes(frame))
    r.depth = depth
    r.ws()
    value = decoder(r)
    r.ws()
    if r.pos != len(r.buf):
        raise r.refuse("trailing_bytes")
    return value


def _service_encode(encoder, value, depth):
    out = bytearray()
    try:
        encoder(out, value, depth)
    except UnicodeError:
        raise Refusal("bad_string", 0) from None
    return bytes(out)


def _service_request(service, method, arguments):
    v = OAServiceFrame(version=1, service=service, method=method, arguments=arguments)
    frame = _service_encode(enc_oaserviceframe, v, 0)
    _service_decode(_decode_oaserviceframe, frame)
    return frame


def _service_check(kind, value, depth=0):
    # Python coercions must not silently change typed service arguments.
    if depth >= _DEPTH_LIMIT and (kind.startswith(("list<", "map<")) or kind in _SERVICE_RECORDS):
        raise Refusal("depth_exceeded", 0)
    if kind == "binary":
        valid = type(value) is bytes
    elif kind == "string":
        valid = type(value) is str
    elif kind in ("i32", "i64"):
        valid = type(value) is int
        if valid:
            limit = 1 << (31 if kind == "i32" else 63)
            if not -limit <= value < limit:
                raise Refusal("number_spelling", 0)
    elif kind == "bool":
        valid = type(value) is bool
    elif kind == "json":
        valid = isinstance(value, (str, bytes, bytearray, memoryview))
    elif kind.startswith("list<"):
        valid = type(value) is list
        if valid:
            for item in value:
                _service_check(kind[5:-1], item, depth + 1)
    elif kind.startswith("map<string,"):
        valid = type(value) is dict
        if valid:
            for key, item in value.items():
                _service_check("string", key, depth + 1)
                _service_check(kind[11:-1], item, depth + 1)
    else:
        cls, fields = _SERVICE_RECORDS[kind]
        valid = isinstance(value, cls)
        if valid:
            for name, field_kind, omit in fields:
                if not hasattr(value, name):
                    raise Refusal("missing_field", 0)
                item = getattr(value, name)
                if omit == "absent" and item is None:
                    continue
                _service_check(field_kind, item, depth + 1)
    if not valid:
        raise Refusal("wrong_type", 0)


class ServiceError(Exception):
    def __init__(self, code, message=""):
        super().__init__(message if message else code)
        self.code = code
        self.message = message


def _service_response(frame, service, method):
    reply = _service_decode(_decode_oaservicereply, frame)
    if reply.version != 1:
        raise DispatchError("unknown_version")
    if reply.service != service or reply.method != method:
        raise DispatchError("mismatched_response")
    if not reply.ok:
        error = _service_decode(_decode_oaserviceerror, reply.payload, 1)
        if not error.code:
            raise DispatchError("invalid_error")
        raise ServiceError(error.code, error.message)
    return reply.payload

_SERVICE_RECORDS = {
    "RequestIdentity": (RequestIdentity, [("key","string","never"),("history_epoch","string","never"),]),
    "Submission": (Submission, [("identity","RequestIdentity","never"),("kind","string","never"),("spec","binary","never"),("required_guarantees","list<string>","never"),]),
    "Receipt": (Receipt, [("identity","RequestIdentity","never"),("logical_owner","string","never"),("operation_id","string","never"),("accepted_guarantees","list<string>","never"),("history_retention_ms","i64","never"),]),
    "AcceptanceResult": (AcceptanceResult, [("outcome","string","never"),("receipt","Receipt","absent"),("reason","string","never"),]),
    "HistoryWindow": (HistoryWindow, [("logical_owner","string","never"),("history_epoch","string","never"),("minimum_retention_ms","i64","never"),]),
    "CancellationResult": (CancellationResult, [("outcome","string","never"),]),
    "OARecoverableAcceptanceGetHistoryWindowArguments": (OARecoverableAcceptanceGetHistoryWindowArguments, []),
    "OARecoverableAcceptanceSubmitArguments": (OARecoverableAcceptanceSubmitArguments, [("submission","Submission","never"),]),
    "OARecoverableAcceptanceReconcileArguments": (OARecoverableAcceptanceReconcileArguments, [("identity","RequestIdentity","never"),]),
    "OARecoverableAcceptanceCancelWorkArguments": (OARecoverableAcceptanceCancelWorkArguments, [("identity","RequestIdentity","never"),]),
    "OAServiceFrame": (OAServiceFrame, [("version","i32","never"),("service","string","never"),("method","string","never"),("arguments","json","never"),]),
    "OAServiceReply": (OAServiceReply, [("version","i32","never"),("service","string","never"),("method","string","never"),("ok","bool","never"),("payload","json","never"),]),
    "OAServiceError": (OAServiceError, [("code","string","never"),("message","string","never"),]),
    "OARecoverableAcceptanceGetHistoryWindowResult": (OARecoverableAcceptanceGetHistoryWindowResult, [("value","HistoryWindow","never"),]),
    "OARecoverableAcceptanceSubmitResult": (OARecoverableAcceptanceSubmitResult, [("value","AcceptanceResult","never"),]),
    "OARecoverableAcceptanceReconcileResult": (OARecoverableAcceptanceReconcileResult, [("value","AcceptanceResult","never"),]),
    "OARecoverableAcceptanceCancelWorkResult": (OARecoverableAcceptanceCancelWorkResult, [("value","CancellationResult","never"),]),
}


class RecoverableAcceptance:
    __doc__ = "Version 1 recoverable acceptance vocabulary, local or remote. Providers must implement atomic recovery and downstream deduplication before advertising those guarantees. Legacy Store is not implicitly upgraded."
    def GetHistoryWindow(self) -> "HistoryWindow":
        raise NotImplementedError
    def Submit(self, submission: "Submission") -> "AcceptanceResult":
        raise NotImplementedError
    def Reconcile(self, identity: "RequestIdentity") -> "AcceptanceResult":
        raise NotImplementedError
    def CancelWork(self, identity: "RequestIdentity") -> "CancellationResult":
        raise NotImplementedError


class RecoverableAcceptanceClient(RecoverableAcceptance):
    def __init__(self, transport):
        self._transport = transport

    def GetHistoryWindow(self) -> "HistoryWindow":
        _oa_args = OARecoverableAcceptanceGetHistoryWindowArguments()
        _oa_arguments = _service_encode(enc_oarecoverableacceptancegethistorywindowarguments, _oa_args, 1)
        _service_decode(_decode_oarecoverableacceptancegethistorywindowarguments, _oa_arguments, 1)
        _oa_request = _service_request("abstraction.job/acceptance@1", "GetHistoryWindow", _oa_arguments)
        _oa_payload = _service_response(self._transport.exchange_frame(_oa_request), "abstraction.job/acceptance@1", "GetHistoryWindow")
        _oa_result = _service_decode(_decode_oarecoverableacceptancegethistorywindowresult, _oa_payload, 1)
        return _oa_result.value

    def Submit(self, submission: "Submission") -> "AcceptanceResult":
        _service_check("Submission", submission)
        _oa_args = OARecoverableAcceptanceSubmitArguments()
        _oa_args.submission = submission
        _oa_arguments = _service_encode(enc_oarecoverableacceptancesubmitarguments, _oa_args, 1)
        _service_decode(_decode_oarecoverableacceptancesubmitarguments, _oa_arguments, 1)
        _oa_request = _service_request("abstraction.job/acceptance@1", "Submit", _oa_arguments)
        _oa_payload = _service_response(self._transport.exchange_frame(_oa_request), "abstraction.job/acceptance@1", "Submit")
        _oa_result = _service_decode(_decode_oarecoverableacceptancesubmitresult, _oa_payload, 1)
        return _oa_result.value

    def Reconcile(self, identity: "RequestIdentity") -> "AcceptanceResult":
        _service_check("RequestIdentity", identity)
        _oa_args = OARecoverableAcceptanceReconcileArguments()
        _oa_args.identity = identity
        _oa_arguments = _service_encode(enc_oarecoverableacceptancereconcilearguments, _oa_args, 1)
        _service_decode(_decode_oarecoverableacceptancereconcilearguments, _oa_arguments, 1)
        _oa_request = _service_request("abstraction.job/acceptance@1", "Reconcile", _oa_arguments)
        _oa_payload = _service_response(self._transport.exchange_frame(_oa_request), "abstraction.job/acceptance@1", "Reconcile")
        _oa_result = _service_decode(_decode_oarecoverableacceptancereconcileresult, _oa_payload, 1)
        return _oa_result.value

    def CancelWork(self, identity: "RequestIdentity") -> "CancellationResult":
        _service_check("RequestIdentity", identity)
        _oa_args = OARecoverableAcceptanceCancelWorkArguments()
        _oa_args.identity = identity
        _oa_arguments = _service_encode(enc_oarecoverableacceptancecancelworkarguments, _oa_args, 1)
        _service_decode(_decode_oarecoverableacceptancecancelworkarguments, _oa_arguments, 1)
        _oa_request = _service_request("abstraction.job/acceptance@1", "CancelWork", _oa_arguments)
        _oa_payload = _service_response(self._transport.exchange_frame(_oa_request), "abstraction.job/acceptance@1", "CancelWork")
        _oa_result = _service_decode(_decode_oarecoverableacceptancecancelworkresult, _oa_payload, 1)
        return _oa_result.value
