// Code generated by abstraction-idl from abstraction-job/acceptance.thrift. DO NOT EDIT.

package acceptance

type Raw = string

func escByte(out []byte, c byte) []byte {
	const hex = "0123456789abcdef"
	switch c {
	case '"':
		return append(out, '\\', '"')
	case '\\':
		return append(out, '\\', '\\')
	case 0x08:
		return append(out, '\\', 'b')
	case 0x0c:
		return append(out, '\\', 'f')
	case '\n':
		return append(out, '\\', 'n')
	case '\r':
		return append(out, '\\', 'r')
	case '\t':
		return append(out, '\\', 't')
	}
	if c < 0x20 {
		return append(out, '\\', 'u', '0', '0', hex[c>>4], hex[c&0xF])
	}
	return append(out, c)
}

func num(out []byte, n int64) []byte {
	if n == 0 {
		return append(out, '0')
	}
	var d [24]byte
	p := len(d)
	u := uint64(n)
	if n < 0 {
		u = -uint64(n)
	}
	for u > 0 {
		p--
		d[p] = byte('0' + u%10)
		u /= 10
	}
	if n < 0 {
		out = append(out, '-')
	}
	return append(out, d[p:]...)
}

func pad(out []byte, depth int) []byte {
	for i := 0; i < depth*2; i++ {
		out = append(out, ' ')
	}
	return out
}

func strs(out []byte, v []string, depth int) []byte {
	if len(v) == 0 {
		return append(out, '[', ']')
	}
	out = append(out, '[', '\n')
	for i, s := range v {
		out = pad(out, depth+1)
		out = esc(out, s)
		if i+1 < len(v) {
			out = append(out, ',')
		}
		out = append(out, '\n')
	}
	out = pad(out, depth)
	return append(out, ']')
}

func raw(out []byte, s string, depth int) []byte {
	ws := func(c byte) bool { return c == ' ' || c == '\t' || c == '\n' || c == '\r' }
	for i := 0; i < len(s); {
		c := s[i]
		if ws(c) {
			i++
			continue
		}
		switch c {
		case '"':
			j := i + 1
			for j < len(s) {
				if s[j] == '\\' {
					j += 2
					continue
				}
				if s[j] == '"' {
					j++
					break
				}
				j++
			}
			out = append(out, s[i:j]...)
			i = j
		case '{', '[':
			out = append(out, c)
			i++
			j := i
			for j < len(s) && ws(s[j]) {
				j++
			}
			if j < len(s) && (s[j] == '}' || s[j] == ']') {
				out = append(out, s[j])
				i = j + 1
			} else {
				depth++
				out = append(out, '\n')
				out = pad(out, depth)
			}
		case '}', ']':
			depth--
			out = append(out, '\n')
			out = pad(out, depth)
			out = append(out, c)
			i++
		case ',':
			out = append(out, ',', '\n')
			out = pad(out, depth)
			i++
		case ':':
			out = append(out, ':', ' ')
			i++
		default:
			out = append(out, c)
			i++
		}
	}
	return out
}

func byteLess(a, b string) bool {
	n := len(a)
	if len(b) < n {
		n = len(b)
	}
	for i := 0; i < n; i++ {
		if a[i] != b[i] {
			return a[i] < b[i]
		}
	}
	return len(a) < len(b)
}

func sortedKeys(m map[string]Raw) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	for i := 1; i < len(keys); i++ {
		for j := i; j > 0 && byteLess(keys[j], keys[j-1]); j-- {
			keys[j], keys[j-1] = keys[j-1], keys[j]
		}
	}
	return keys
}

func rawmap(out []byte, m map[string]Raw, depth int) []byte {
	keys := sortedKeys(m)
	if len(keys) == 0 {
		return append(out, '{', '}')
	}
	out = append(out, '{', '\n')
	for i, k := range keys {
		out = pad(out, depth+1)
		out = esc(out, k)
		out = append(out, ':', ' ')
		out = raw(out, m[k], depth+1)
		if i+1 < len(keys) {
			out = append(out, ',')
		}
		out = append(out, '\n')
	}
	out = pad(out, depth)
	return append(out, '}')
}

func esc(out []byte, s string) []byte {
	out = append(out, '"')
	for i := 0; i < len(s); i++ {
		out = escByte(out, s[i])
	}
	return append(out, '"')
}

var OutcomeNames = []string{"accepted", "definitely_not_accepted", "unknown", "key_conflict", "forbidden", "invalid"}

const OutcomeAccepted = "accepted"

const OutcomeDefinitelyNotAccepted = "definitely_not_accepted"

const OutcomeUnknown = "unknown"

const OutcomeKeyConflict = "key_conflict"

const OutcomeForbidden = "forbidden"

const OutcomeInvalid = "invalid"

const OutcomeUnknownPolicy = "refuse"

var CancellationOutcomeNames = []string{"requested", "already_terminal", "unknown", "forbidden", "unsupported"}

const CancellationOutcomeRequested = "requested"

const CancellationOutcomeAlreadyTerminal = "already_terminal"

const CancellationOutcomeUnknown = "unknown"

const CancellationOutcomeForbidden = "forbidden"

const CancellationOutcomeUnsupported = "unsupported"

const CancellationOutcomeUnknownPolicy = "refuse"

type RequestIdentity struct {
	Key          string
	HistoryEpoch string
}

type Submission struct {
	Identity           RequestIdentity
	Kind               string
	Spec               []byte
	RequiredGuarantees []string
}

type Receipt struct {
	Identity           RequestIdentity
	LogicalOwner       string
	OperationId        string
	AcceptedGuarantees []string
	HistoryRetentionMs int64
}

type AcceptanceResult struct {
	Outcome string
	Receipt *Receipt
	Reason  string
}

type HistoryWindow struct {
	LogicalOwner       string
	HistoryEpoch       string
	MinimumRetentionMs int64
}

type CancellationResult struct {
	Outcome string
}

type OARecoverableAcceptanceGetHistoryWindowArguments struct {
}

type OARecoverableAcceptanceSubmitArguments struct {
	Submission Submission
}

type OARecoverableAcceptanceReconcileArguments struct {
	Identity RequestIdentity
}

type OARecoverableAcceptanceCancelWorkArguments struct {
	Identity RequestIdentity
}

type OAServiceFrame struct {
	Version   int32
	Service   string
	Method    string
	Arguments Raw
}

type OAServiceReply struct {
	Version int32
	Service string
	Method  string
	Ok      bool
	Payload Raw
}

type OAServiceError struct {
	Code    string
	Message string
}

type OARecoverableAcceptanceGetHistoryWindowResult struct {
	Value HistoryWindow
}

type OARecoverableAcceptanceSubmitResult struct {
	Value AcceptanceResult
}

type OARecoverableAcceptanceReconcileResult struct {
	Value AcceptanceResult
}

type OARecoverableAcceptanceCancelWorkResult struct {
	Value CancellationResult
}

func encRequestIdentity(out []byte, v *RequestIdentity, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "key")
	out = append(out, ':', ' ')
	out = esc(out, v.Key)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "history_epoch")
	out = append(out, ':', ' ')
	out = esc(out, v.HistoryEpoch)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encSubmission(out []byte, v *Submission, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "identity")
	out = append(out, ':', ' ')
	out = encRequestIdentity(out, &v.Identity, depth+1)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "kind")
	out = append(out, ':', ' ')
	out = esc(out, v.Kind)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "spec")
	out = append(out, ':', ' ')
	out = esc(out, encodeBinary(v.Spec))
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "required_guarantees")
	out = append(out, ':', ' ')
	out = strs(out, v.RequiredGuarantees, depth+1)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encReceipt(out []byte, v *Receipt, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "identity")
	out = append(out, ':', ' ')
	out = encRequestIdentity(out, &v.Identity, depth+1)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "logical_owner")
	out = append(out, ':', ' ')
	out = esc(out, v.LogicalOwner)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "operation_id")
	out = append(out, ':', ' ')
	out = esc(out, v.OperationId)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "accepted_guarantees")
	out = append(out, ':', ' ')
	out = strs(out, v.AcceptedGuarantees, depth+1)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "history_retention_ms")
	out = append(out, ':', ' ')
	out = num(out, v.HistoryRetentionMs)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encAcceptanceResult(out []byte, v *AcceptanceResult, depth int) []byte {
	if v.Outcome != "accepted" && v.Outcome != "definitely_not_accepted" && v.Outcome != "unknown" && v.Outcome != "key_conflict" && v.Outcome != "forbidden" && v.Outcome != "invalid" {
		panic(&Refusal{Word: "bad_enum", Offset: 0})
	}
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "outcome")
	out = append(out, ':', ' ')
	out = esc(out, v.Outcome)
	if v.Receipt != nil {
		out = append(out, ',')
		out = append(out, '\n')
		out = pad(out, depth+1)
		out = esc(out, "receipt")
		out = append(out, ':', ' ')
		out = encReceipt(out, v.Receipt, depth+1)
	}
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "reason")
	out = append(out, ':', ' ')
	out = esc(out, v.Reason)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encHistoryWindow(out []byte, v *HistoryWindow, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "logical_owner")
	out = append(out, ':', ' ')
	out = esc(out, v.LogicalOwner)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "history_epoch")
	out = append(out, ':', ' ')
	out = esc(out, v.HistoryEpoch)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "minimum_retention_ms")
	out = append(out, ':', ' ')
	out = num(out, v.MinimumRetentionMs)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encCancellationResult(out []byte, v *CancellationResult, depth int) []byte {
	if v.Outcome != "requested" && v.Outcome != "already_terminal" && v.Outcome != "unknown" && v.Outcome != "forbidden" && v.Outcome != "unsupported" {
		panic(&Refusal{Word: "bad_enum", Offset: 0})
	}
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "outcome")
	out = append(out, ':', ' ')
	out = esc(out, v.Outcome)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOARecoverableAcceptanceGetHistoryWindowArguments(out []byte, v *OARecoverableAcceptanceGetHistoryWindowArguments, depth int) []byte {
	out = append(out, '{')
	return append(out, '}')
}

func encOARecoverableAcceptanceSubmitArguments(out []byte, v *OARecoverableAcceptanceSubmitArguments, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "submission")
	out = append(out, ':', ' ')
	out = encSubmission(out, &v.Submission, depth+1)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOARecoverableAcceptanceReconcileArguments(out []byte, v *OARecoverableAcceptanceReconcileArguments, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "identity")
	out = append(out, ':', ' ')
	out = encRequestIdentity(out, &v.Identity, depth+1)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOARecoverableAcceptanceCancelWorkArguments(out []byte, v *OARecoverableAcceptanceCancelWorkArguments, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "identity")
	out = append(out, ':', ' ')
	out = encRequestIdentity(out, &v.Identity, depth+1)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOAServiceFrame(out []byte, v *OAServiceFrame, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "version")
	out = append(out, ':', ' ')
	out = num(out, int64(v.Version))
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "service")
	out = append(out, ':', ' ')
	out = esc(out, v.Service)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "method")
	out = append(out, ':', ' ')
	out = esc(out, v.Method)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "arguments")
	out = append(out, ':', ' ')
	out = append(out, v.Arguments...)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOAServiceReply(out []byte, v *OAServiceReply, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "version")
	out = append(out, ':', ' ')
	out = num(out, int64(v.Version))
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "service")
	out = append(out, ':', ' ')
	out = esc(out, v.Service)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "method")
	out = append(out, ':', ' ')
	out = esc(out, v.Method)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "ok")
	out = append(out, ':', ' ')
	if v.Ok {
		out = append(out, 't', 'r', 'u', 'e')
	} else {
		out = append(out, 'f', 'a', 'l', 's', 'e')
	}
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "payload")
	out = append(out, ':', ' ')
	out = append(out, v.Payload...)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOAServiceError(out []byte, v *OAServiceError, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "code")
	out = append(out, ':', ' ')
	out = esc(out, v.Code)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "message")
	out = append(out, ':', ' ')
	out = esc(out, v.Message)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOARecoverableAcceptanceGetHistoryWindowResult(out []byte, v *OARecoverableAcceptanceGetHistoryWindowResult, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "value")
	out = append(out, ':', ' ')
	out = encHistoryWindow(out, &v.Value, depth+1)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOARecoverableAcceptanceSubmitResult(out []byte, v *OARecoverableAcceptanceSubmitResult, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "value")
	out = append(out, ':', ' ')
	out = encAcceptanceResult(out, &v.Value, depth+1)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOARecoverableAcceptanceReconcileResult(out []byte, v *OARecoverableAcceptanceReconcileResult, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "value")
	out = append(out, ':', ' ')
	out = encAcceptanceResult(out, &v.Value, depth+1)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOARecoverableAcceptanceCancelWorkResult(out []byte, v *OARecoverableAcceptanceCancelWorkResult, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "value")
	out = append(out, ':', ' ')
	out = encCancellationResult(out, &v.Value, depth+1)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func Encode(v *AcceptanceResult) []byte {
	return append(encAcceptanceResult(nil, v, 0), '\n')
}

type Refusal struct {
	Word   string
	Offset int
}

func (r *Refusal) Error() string {
	return "refused: " + r.Word + " at byte " + decimal(int64(r.Offset))
}

func decimal(n int64) string { return string(num(nil, n)) }

const depthLimit = 64

type reader struct {
	buf   []byte
	pos   int
	depth int
}

func (r *reader) refuse(word string) error { return &Refusal{Word: word, Offset: r.pos} }

func (r *reader) at() byte {
	if r.pos < len(r.buf) {
		return r.buf[r.pos]
	}
	return 0
}

func (r *reader) ws() {
	for r.pos < len(r.buf) {
		switch r.buf[r.pos] {
		case ' ', '\t', '\n', '\r':
			r.pos++
		default:
			return
		}
	}
}

func (r *reader) enter() error {
	r.depth++
	if r.depth > depthLimit {
		return r.refuse("depth_exceeded")
	}
	return nil
}

func (r *reader) str() (string, error) {
	if r.at() != '"' {
		return "", r.refuse("wrong_type")
	}
	r.pos++
	var out []byte
	for {
		if r.pos >= len(r.buf) {
			return "", r.refuse("malformed")
		}
		c := r.buf[r.pos]
		switch {
		case c == '"':
			r.pos++
			if !validUTF8(out) {
				return "", r.refuse("bad_string")
			}
			return string(out), nil
		case c < 0x20:
			return "", r.refuse("bad_string")
		case c == '\\':
			var err error
			if out, err = r.escape(out); err != nil {
				return "", err
			}
		default:
			out = append(out, c)
			r.pos++
		}
	}
}

func (r *reader) escape(out []byte) ([]byte, error) {
	r.pos++
	if r.pos >= len(r.buf) {
		return nil, r.refuse("malformed")
	}
	c := r.buf[r.pos]
	r.pos++
	switch c {
	case '"', '\\', '/':
		return append(out, c), nil
	case 'b':
		return append(out, 0x08), nil
	case 'f':
		return append(out, 0x0c), nil
	case 'n':
		return append(out, '\n'), nil
	case 'r':
		return append(out, '\r'), nil
	case 't':
		return append(out, '\t'), nil
	case 'u':
		u, err := r.hex4()
		if err != nil {
			return nil, err
		}
		if u >= 0xDC00 && u <= 0xDFFF {
			return nil, r.refuse("bad_string")
		}
		if u >= 0xD800 && u <= 0xDBFF {
			if r.pos+1 >= len(r.buf) || r.buf[r.pos] != '\\' || r.buf[r.pos+1] != 'u' {
				return nil, r.refuse("bad_string")
			}
			r.pos += 2
			lo, err := r.hex4()
			if err != nil {
				return nil, err
			}
			if lo < 0xDC00 || lo > 0xDFFF {
				return nil, r.refuse("bad_string")
			}
			u = 0x10000 + (u-0xD800)<<10 + (lo - 0xDC00)
		}
		return appendRune(out, u), nil
	}
	return nil, r.refuse("bad_string")
}

func (r *reader) hex4() (int32, error) {
	if r.pos+4 > len(r.buf) {
		return 0, r.refuse("bad_string")
	}
	var u int32
	for i := 0; i < 4; i++ {
		c := r.buf[r.pos+i]
		switch {
		case c >= '0' && c <= '9':
			u = u<<4 | int32(c-'0')
		case c >= 'a' && c <= 'f':
			u = u<<4 | int32(c-'a'+10)
		case c >= 'A' && c <= 'F':
			u = u<<4 | int32(c-'A'+10)
		default:
			return 0, r.refuse("bad_string")
		}
	}
	r.pos += 4
	return u, nil
}

func appendRune(out []byte, cp int32) []byte {
	switch {
	case cp < 0x80:
		return append(out, byte(cp))
	case cp < 0x800:
		return append(out, byte(0xC0|cp>>6), byte(0x80|cp&0x3F))
	case cp < 0x10000:
		return append(out, byte(0xE0|cp>>12), byte(0x80|cp>>6&0x3F), byte(0x80|cp&0x3F))
	}
	return append(out, byte(0xF0|cp>>18), byte(0x80|cp>>12&0x3F), byte(0x80|cp>>6&0x3F), byte(0x80|cp&0x3F))
}

func validUTF8(b []byte) bool {
	for i := 0; i < len(b); {
		c := b[i]
		var n int
		var cp int32
		switch {
		case c < 0x80:
			i++
			continue
		case c>>5 == 0x6:
			n, cp = 2, int32(c&0x1F)
		case c>>4 == 0xE:
			n, cp = 3, int32(c&0x0F)
		case c>>3 == 0x1E:
			n, cp = 4, int32(c&0x07)
		default:
			return false
		}
		if i+n > len(b) {
			return false
		}
		for k := 1; k < n; k++ {
			if b[i+k]>>6 != 0x2 {
				return false
			}
			cp = cp<<6 | int32(b[i+k]&0x3F)
		}
		lowest := []int32{0, 0, 0x80, 0x800, 0x10000}[n]
		if cp < lowest || cp > 0x10FFFF || (cp >= 0xD800 && cp <= 0xDFFF) {
			return false
		}
		i += n
	}
	return true
}

func (r *reader) integer(min, max int64) (int64, error) {
	c := r.at()
	if c != '-' && (c < '0' || c > '9') {
		return 0, r.refuse("wrong_type")
	}
	neg := c == '-'
	if neg {
		r.pos++
	}
	d := r.at()
	if d < '0' || d > '9' {
		return 0, r.refuse("malformed")
	}
	var u uint64
	if d == '0' {
		r.pos++
	} else {
		for d = r.at(); d >= '0' && d <= '9'; d = r.at() {
			if u > 922337203685477580 {
				return 0, r.refuse("number_spelling")
			}
			u = u*10 + uint64(d-'0')
			r.pos++
		}
	}
	switch c := r.at(); {
	case c == '.' || c == 'e' || c == 'E' || (c >= '0' && c <= '9'):
		return 0, r.refuse("number_spelling")
	}
	if neg && u == 0 {
		return 0, r.refuse("number_spelling")
	}
	var n int64
	switch {
	case neg && u == 1<<63:
		n = -1 << 63
	case u > 1<<63-1:
		return 0, r.refuse("number_spelling")
	case neg:
		n = -int64(u)
	default:
		n = int64(u)
	}
	if n < min || n > max {
		return 0, r.refuse("number_spelling")
	}
	return n, nil
}

func (r *reader) boolean() (bool, error) {
	switch r.at() {
	case 't':
		return true, r.literal("true")
	case 'f':
		return false, r.literal("false")
	}
	return false, r.refuse("wrong_type")
}

func (r *reader) literal(word string) error {
	if r.pos+len(word) > len(r.buf) || string(r.buf[r.pos:r.pos+len(word)]) != word {
		return r.refuse("malformed")
	}
	r.pos += len(word)
	return nil
}

func (r *reader) strList() ([]string, error) {
	if r.at() != '[' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	out := []string{}
	r.ws()
	if r.at() != ']' {
		for {
			r.ws()
			s, err := r.str()
			if err != nil {
				return nil, err
			}
			out = append(out, s)
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != ']' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	return out, nil
}

func (r *reader) rawMap() (map[string]Raw, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	out := map[string]Raw{}
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			k, err := r.str()
			if err != nil {
				return nil, err
			}
			if _, again := out[k]; again {
				return nil, r.refuse("duplicate_key")
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			v, err := r.rawValue()
			if err != nil {
				return nil, err
			}
			out[k] = v
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	return out, nil
}

func (r *reader) rawValue() (Raw, error) {
	start := r.pos
	if err := r.skipValue(); err != nil {
		return "", err
	}
	return Raw(r.buf[start:r.pos]), nil
}

func (r *reader) skipValue() error {
	c := r.at()
	switch {
	case c == '"':
		return r.skipString()
	case c == '{' || c == '[':
		return r.skipContainer()
	case c == 't':
		return r.literal("true")
	case c == 'f':
		return r.literal("false")
	case c == 'n':
		return r.literal("null")
	case c == '-' || (c >= '0' && c <= '9'):
		return r.skipNumber()
	}
	return r.refuse("malformed")
}

// An opaque value is validated and carried, never interpreted. Its syntax is
// the record's own — the same string reader, so an escape, a control byte or a
// lone surrogate is judged identically at any depth — and what it is free to
// spell, it keeps: the bytes between these two offsets are what a writer
// re-emits. A number is walked, never converted, so a value no host type holds
// survives the reader that carried it.
func (r *reader) skipString() error {
	_, err := r.str()
	return err
}

func (r *reader) skipNumber() error {
	if r.at() == '-' {
		r.pos++
	}
	switch c := r.at(); {
	case c == '0':
		r.pos++
	case c >= '1' && c <= '9':
		for c := r.at(); c >= '0' && c <= '9'; c = r.at() {
			r.pos++
		}
	default:
		return r.refuse("number_spelling")
	}
	if r.at() == '.' {
		r.pos++
		if err := r.someDigits(); err != nil {
			return err
		}
	}
	if c := r.at(); c == 'e' || c == 'E' {
		r.pos++
		if c := r.at(); c == '+' || c == '-' {
			r.pos++
		}
		if err := r.someDigits(); err != nil {
			return err
		}
	}
	return nil
}

func (r *reader) someDigits() error {
	n := 0
	for c := r.at(); c >= '0' && c <= '9'; c = r.at() {
		r.pos++
		n++
	}
	if n == 0 {
		return r.refuse("number_spelling")
	}
	return nil
}

func (r *reader) skipContainer() error {
	open := r.buf[r.pos]
	shut := byte('}')
	if open == '[' {
		shut = ']'
	}
	if err := r.enter(); err != nil {
		return err
	}
	r.pos++
	r.ws()
	seen := map[string]bool{}
	if r.at() != shut {
		for {
			r.ws()
			if open == '{' {
				if r.at() != '"' {
					return r.refuse("malformed")
				}
				k, err := r.str()
				if err != nil {
					return err
				}
				if seen[k] {
					return r.refuse("duplicate_key")
				}
				seen[k] = true
				r.ws()
				if r.at() != ':' {
					return r.refuse("malformed")
				}
				r.pos++
				r.ws()
			}
			if err := r.skipValue(); err != nil {
				return err
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != shut {
		return r.refuse("malformed")
	}
	r.pos++
	r.depth--
	return nil
}

func (r *reader) decodeRequestIdentity() (*RequestIdentity, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &RequestIdentity{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "key":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Key = x
			case "history_epoch":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.HistoryEpoch = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&3 != 3 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeSubmission() (*Submission, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &Submission{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "identity":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.decodeRequestIdentity()
				if err != nil {
					return nil, err
				}
				v.Identity = *x
			case "kind":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Kind = x
			case "spec":
				if seen&4 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 4
				x, err := r.binary()
				if err != nil {
					return nil, err
				}
				v.Spec = x
			case "required_guarantees":
				if seen&8 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 8
				x, err := r.strList()
				if err != nil {
					return nil, err
				}
				v.RequiredGuarantees = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&15 != 15 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeReceipt() (*Receipt, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &Receipt{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "identity":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.decodeRequestIdentity()
				if err != nil {
					return nil, err
				}
				v.Identity = *x
			case "logical_owner":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.LogicalOwner = x
			case "operation_id":
				if seen&4 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 4
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.OperationId = x
			case "accepted_guarantees":
				if seen&8 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 8
				x, err := r.strList()
				if err != nil {
					return nil, err
				}
				v.AcceptedGuarantees = x
			case "history_retention_ms":
				if seen&16 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 16
				x, err := r.integer(-9223372036854775808, 9223372036854775807)
				if err != nil {
					return nil, err
				}
				v.HistoryRetentionMs = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&31 != 31 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeAcceptanceResult() (*AcceptanceResult, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &AcceptanceResult{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "outcome":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Outcome = x
			case "receipt":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.decodeReceipt()
				if err != nil {
					return nil, err
				}
				v.Receipt = x
			case "reason":
				if seen&4 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 4
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Reason = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&5 != 5 {
		return nil, r.refuse("missing_field")
	}
	if v.Outcome != "accepted" && v.Outcome != "definitely_not_accepted" && v.Outcome != "unknown" && v.Outcome != "key_conflict" && v.Outcome != "forbidden" && v.Outcome != "invalid" {
		return nil, r.refuse("bad_enum")
	}
	return v, nil
}

func (r *reader) decodeHistoryWindow() (*HistoryWindow, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &HistoryWindow{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "logical_owner":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.LogicalOwner = x
			case "history_epoch":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.HistoryEpoch = x
			case "minimum_retention_ms":
				if seen&4 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 4
				x, err := r.integer(-9223372036854775808, 9223372036854775807)
				if err != nil {
					return nil, err
				}
				v.MinimumRetentionMs = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&7 != 7 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeCancellationResult() (*CancellationResult, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &CancellationResult{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "outcome":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Outcome = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&1 != 1 {
		return nil, r.refuse("missing_field")
	}
	if v.Outcome != "requested" && v.Outcome != "already_terminal" && v.Outcome != "unknown" && v.Outcome != "forbidden" && v.Outcome != "unsupported" {
		return nil, r.refuse("bad_enum")
	}
	return v, nil
}

func (r *reader) decodeOARecoverableAcceptanceGetHistoryWindowArguments() (*OARecoverableAcceptanceGetHistoryWindowArguments, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &OARecoverableAcceptanceGetHistoryWindowArguments{}
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	return v, nil
}

func (r *reader) decodeOARecoverableAcceptanceSubmitArguments() (*OARecoverableAcceptanceSubmitArguments, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &OARecoverableAcceptanceSubmitArguments{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "submission":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.decodeSubmission()
				if err != nil {
					return nil, err
				}
				v.Submission = *x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&1 != 1 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOARecoverableAcceptanceReconcileArguments() (*OARecoverableAcceptanceReconcileArguments, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &OARecoverableAcceptanceReconcileArguments{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "identity":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.decodeRequestIdentity()
				if err != nil {
					return nil, err
				}
				v.Identity = *x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&1 != 1 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOARecoverableAcceptanceCancelWorkArguments() (*OARecoverableAcceptanceCancelWorkArguments, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &OARecoverableAcceptanceCancelWorkArguments{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "identity":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.decodeRequestIdentity()
				if err != nil {
					return nil, err
				}
				v.Identity = *x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&1 != 1 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOAServiceFrame() (*OAServiceFrame, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &OAServiceFrame{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "version":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.integer(-2147483648, 2147483647)
				if err != nil {
					return nil, err
				}
				v.Version = int32(x)
			case "service":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Service = x
			case "method":
				if seen&4 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 4
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Method = x
			case "arguments":
				if seen&8 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 8
				x, err := r.rawValue()
				if err != nil {
					return nil, err
				}
				v.Arguments = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&15 != 15 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOAServiceReply() (*OAServiceReply, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &OAServiceReply{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "version":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.integer(-2147483648, 2147483647)
				if err != nil {
					return nil, err
				}
				v.Version = int32(x)
			case "service":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Service = x
			case "method":
				if seen&4 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 4
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Method = x
			case "ok":
				if seen&8 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 8
				x, err := r.boolean()
				if err != nil {
					return nil, err
				}
				v.Ok = x
			case "payload":
				if seen&16 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 16
				x, err := r.rawValue()
				if err != nil {
					return nil, err
				}
				v.Payload = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&31 != 31 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOAServiceError() (*OAServiceError, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &OAServiceError{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "code":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Code = x
			case "message":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Message = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&3 != 3 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOARecoverableAcceptanceGetHistoryWindowResult() (*OARecoverableAcceptanceGetHistoryWindowResult, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &OARecoverableAcceptanceGetHistoryWindowResult{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "value":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.decodeHistoryWindow()
				if err != nil {
					return nil, err
				}
				v.Value = *x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&1 != 1 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOARecoverableAcceptanceSubmitResult() (*OARecoverableAcceptanceSubmitResult, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &OARecoverableAcceptanceSubmitResult{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "value":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.decodeAcceptanceResult()
				if err != nil {
					return nil, err
				}
				v.Value = *x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&1 != 1 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOARecoverableAcceptanceReconcileResult() (*OARecoverableAcceptanceReconcileResult, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &OARecoverableAcceptanceReconcileResult{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "value":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.decodeAcceptanceResult()
				if err != nil {
					return nil, err
				}
				v.Value = *x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&1 != 1 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOARecoverableAcceptanceCancelWorkResult() (*OARecoverableAcceptanceCancelWorkResult, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &OARecoverableAcceptanceCancelWorkResult{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "value":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.decodeCancellationResult()
				if err != nil {
					return nil, err
				}
				v.Value = *x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&1 != 1 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func Decode(in []byte) (*AcceptanceResult, error) {
	r := &reader{buf: in}
	r.ws()
	v, err := r.decodeAcceptanceResult()
	if err != nil {
		return nil, err
	}
	r.ws()
	if r.pos < len(r.buf) {
		return nil, r.refuse("trailing_bytes")
	}
	return v, nil
}

// Refusals is in the order two of them are chosen between.

var Refusals = []string{"malformed", "bad_string", "number_spelling", "wrong_type", "depth_exceeded", "duplicate_key", "duplicate_field", "unknown_field", "missing_field", "bad_binary", "bad_enum", "trailing_bytes"}

func RefusalRank(word string) int {
	for i, w := range Refusals {
		if w == word {
			return i
		}
	}
	return -1
}

func encodeBinary(value []byte) string {
	const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
	out := make([]byte, 0, ((len(value)+2)/3)*4)
	for i := 0; i < len(value); i += 3 {
		n := len(value) - i
		v := uint32(value[i]) << 16
		if n > 1 {
			v |= uint32(value[i+1]) << 8
		}
		if n > 2 {
			v |= uint32(value[i+2])
		}
		out = append(out, alphabet[v>>18], alphabet[(v>>12)&63])
		if n > 1 {
			out = append(out, alphabet[(v>>6)&63])
		} else {
			out = append(out, '=')
		}
		if n > 2 {
			out = append(out, alphabet[v&63])
		} else {
			out = append(out, '=')
		}
	}
	return string(out)
}
func (r *reader) binary() ([]byte, error) {
	text, err := r.str()
	if err != nil {
		return nil, err
	}
	const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
	if len(text)%4 != 0 {
		return nil, r.refuse("bad_binary")
	}
	out := make([]byte, 0, len(text)/4*3)
	for i := 0; i < len(text); i += 4 {
		var v uint32
		pad := 0
		for j := 0; j < 4; j++ {
			c := text[i+j]
			digit := -1
			if c == '=' {
				if j < 2 || i+4 != len(text) {
					return nil, r.refuse("bad_binary")
				}
				pad++
				digit = 0
			} else {
				if pad != 0 {
					return nil, r.refuse("bad_binary")
				}
				for k := 0; k < len(alphabet); k++ {
					if alphabet[k] == c {
						digit = k
						break
					}
				}
			}
			if digit < 0 {
				return nil, r.refuse("bad_binary")
			}
			v = (v << 6) | uint32(digit)
		}
		out = append(out, byte(v>>16))
		if pad < 2 {
			out = append(out, byte(v>>8))
		}
		if pad == 0 {
			out = append(out, byte(v))
		}
	}
	if encodeBinary(out) != text {
		return nil, r.refuse("bad_binary")
	}
	return out, nil
}

// A transport consumes or copies frames before returning. WriteFrame is one-way.
type FrameWriter interface{ WriteFrame([]byte) error }
type DispatchError string

func (e DispatchError) Error() string { return string(e) }
func servicePayload(frame []byte) (*OAServiceFrame, error) {
	r := &reader{buf: frame}
	r.ws()
	v, err := r.decodeOAServiceFrame()
	if err != nil {
		return nil, err
	}
	r.ws()
	if r.pos != len(r.buf) {
		return nil, r.refuse("trailing_bytes")
	}
	if v.Version != 1 {
		return nil, DispatchError("unknown_version")
	}
	return v, nil
}

// ExchangeFrame returns the response associated with this call. Correlation,
// serialization and deadlines belong to the transport, not this codec.
type FrameExchanger interface{ ExchangeFrame([]byte) ([]byte, error) }
type ServiceError struct {
	Code    string
	Message string
}

func (e *ServiceError) Error() string {
	if e.Message != "" {
		return e.Message
	}
	return e.Code
}
func serviceResponse(frame []byte, service, method string) (Raw, error) {
	r := &reader{buf: frame}
	r.ws()
	v, err := r.decodeOAServiceReply()
	if err != nil {
		return "", err
	}
	r.ws()
	if r.pos != len(r.buf) {
		return "", r.refuse("trailing_bytes")
	}
	if v.Version != 1 {
		return "", DispatchError("unknown_version")
	}
	if v.Service != service || v.Method != method {
		return "", DispatchError("mismatched_response")
	}
	if !v.Ok {
		r = &reader{buf: []byte(v.Payload), depth: 1}
		r.ws()
		e, err := r.decodeOAServiceError()
		if err != nil {
			return "", err
		}
		r.ws()
		if r.pos != len(r.buf) {
			return "", r.refuse("trailing_bytes")
		}
		if e.Code == "" {
			return "", DispatchError("invalid_error")
		}
		return "", &ServiceError{Code: e.Code, Message: e.Message}
	}
	return v.Payload, nil
}
func serviceReply(v *OAServiceFrame, payload Raw, err error) (frame []byte, outErr error) {
	defer func() {
		if p := recover(); p != nil {
			if e, ok := p.(*Refusal); ok {
				frame = nil
				outErr = e
			} else {
				panic(p)
			}
		}
	}()
	reply := OAServiceReply{Version: 1, Service: v.Service, Method: v.Method, Ok: err == nil, Payload: payload}
	if err != nil {
		e := OAServiceError{Code: "handler_error", Message: "handler failed"}
		switch x := err.(type) {
		case *ServiceError:
			if x.Code != "" {
				e.Code = x.Code
			}
			e.Message = x.Message
		case DispatchError:
			e.Code = string(x)
			e.Message = ""
		case *Refusal:
			e.Code = x.Word
			e.Message = ""
		}
		reply.Payload = Raw(encOAServiceError(nil, &e, 1))
	}
	frame = encOAServiceReply(nil, &reply, 0)
	// Validate even error diagnostics before making them visible on the wire.
	r := &reader{buf: frame}
	r.ws()
	if _, e := r.decodeOAServiceReply(); e != nil {
		return nil, e
	}
	return frame, nil
}

type RecoverableAcceptance interface {
	GetHistoryWindow() (HistoryWindow, error)
	Submit(Submission) (AcceptanceResult, error)
	Reconcile(RequestIdentity) (AcceptanceResult, error)
	CancelWork(RequestIdentity) (CancellationResult, error)
}
type RecoverableAcceptanceTransport interface {
	FrameExchanger
}
type RecoverableAcceptanceClient struct {
	transport RecoverableAcceptanceTransport
}

func NewRecoverableAcceptanceClient(t RecoverableAcceptanceTransport) *RecoverableAcceptanceClient {
	return &RecoverableAcceptanceClient{transport: t}
}

type RecoverableAcceptanceDispatcher struct{ Handler RecoverableAcceptance }

func (c *RecoverableAcceptanceClient) GetHistoryWindow() (result HistoryWindow, err error) {
	defer func() {
		if p := recover(); p != nil {
			if e, ok := p.(*Refusal); ok {
				err = e
			} else {
				panic(p)
			}
		}
	}()
	args := OARecoverableAcceptanceGetHistoryWindowArguments{}
	v := OAServiceFrame{Version: 1, Service: "abstraction.job/acceptance@1", Method: "GetHistoryWindow", Arguments: Raw(encOARecoverableAcceptanceGetHistoryWindowArguments(nil, &args, 1))}
	frame := encOAServiceFrame(nil, &v, 0)
	if _, err = servicePayload(frame); err != nil {
		return
	}
	var response []byte
	response, err = c.transport.ExchangeFrame(frame)
	if err != nil {
		return
	}
	var payload Raw
	payload, err = serviceResponse(response, v.Service, v.Method)
	if err != nil {
		return
	}
	r := &reader{buf: []byte(payload), depth: 1}
	r.ws()
	var decoded *OARecoverableAcceptanceGetHistoryWindowResult
	decoded, err = r.decodeOARecoverableAcceptanceGetHistoryWindowResult()
	if err != nil {
		return
	}
	_ = decoded
	r.ws()
	if r.pos != len(r.buf) {
		err = r.refuse("trailing_bytes")
		return
	}
	result = decoded.Value
	return
}
func (c *RecoverableAcceptanceClient) Submit(arg0 Submission) (result AcceptanceResult, err error) {
	defer func() {
		if p := recover(); p != nil {
			if e, ok := p.(*Refusal); ok {
				err = e
			} else {
				panic(p)
			}
		}
	}()
	args := OARecoverableAcceptanceSubmitArguments{Submission: arg0}
	v := OAServiceFrame{Version: 1, Service: "abstraction.job/acceptance@1", Method: "Submit", Arguments: Raw(encOARecoverableAcceptanceSubmitArguments(nil, &args, 1))}
	frame := encOAServiceFrame(nil, &v, 0)
	if _, err = servicePayload(frame); err != nil {
		return
	}
	var response []byte
	response, err = c.transport.ExchangeFrame(frame)
	if err != nil {
		return
	}
	var payload Raw
	payload, err = serviceResponse(response, v.Service, v.Method)
	if err != nil {
		return
	}
	r := &reader{buf: []byte(payload), depth: 1}
	r.ws()
	var decoded *OARecoverableAcceptanceSubmitResult
	decoded, err = r.decodeOARecoverableAcceptanceSubmitResult()
	if err != nil {
		return
	}
	_ = decoded
	r.ws()
	if r.pos != len(r.buf) {
		err = r.refuse("trailing_bytes")
		return
	}
	result = decoded.Value
	return
}
func (c *RecoverableAcceptanceClient) Reconcile(arg0 RequestIdentity) (result AcceptanceResult, err error) {
	defer func() {
		if p := recover(); p != nil {
			if e, ok := p.(*Refusal); ok {
				err = e
			} else {
				panic(p)
			}
		}
	}()
	args := OARecoverableAcceptanceReconcileArguments{Identity: arg0}
	v := OAServiceFrame{Version: 1, Service: "abstraction.job/acceptance@1", Method: "Reconcile", Arguments: Raw(encOARecoverableAcceptanceReconcileArguments(nil, &args, 1))}
	frame := encOAServiceFrame(nil, &v, 0)
	if _, err = servicePayload(frame); err != nil {
		return
	}
	var response []byte
	response, err = c.transport.ExchangeFrame(frame)
	if err != nil {
		return
	}
	var payload Raw
	payload, err = serviceResponse(response, v.Service, v.Method)
	if err != nil {
		return
	}
	r := &reader{buf: []byte(payload), depth: 1}
	r.ws()
	var decoded *OARecoverableAcceptanceReconcileResult
	decoded, err = r.decodeOARecoverableAcceptanceReconcileResult()
	if err != nil {
		return
	}
	_ = decoded
	r.ws()
	if r.pos != len(r.buf) {
		err = r.refuse("trailing_bytes")
		return
	}
	result = decoded.Value
	return
}
func (c *RecoverableAcceptanceClient) CancelWork(arg0 RequestIdentity) (result CancellationResult, err error) {
	defer func() {
		if p := recover(); p != nil {
			if e, ok := p.(*Refusal); ok {
				err = e
			} else {
				panic(p)
			}
		}
	}()
	args := OARecoverableAcceptanceCancelWorkArguments{Identity: arg0}
	v := OAServiceFrame{Version: 1, Service: "abstraction.job/acceptance@1", Method: "CancelWork", Arguments: Raw(encOARecoverableAcceptanceCancelWorkArguments(nil, &args, 1))}
	frame := encOAServiceFrame(nil, &v, 0)
	if _, err = servicePayload(frame); err != nil {
		return
	}
	var response []byte
	response, err = c.transport.ExchangeFrame(frame)
	if err != nil {
		return
	}
	var payload Raw
	payload, err = serviceResponse(response, v.Service, v.Method)
	if err != nil {
		return
	}
	r := &reader{buf: []byte(payload), depth: 1}
	r.ws()
	var decoded *OARecoverableAcceptanceCancelWorkResult
	decoded, err = r.decodeOARecoverableAcceptanceCancelWorkResult()
	if err != nil {
		return
	}
	_ = decoded
	r.ws()
	if r.pos != len(r.buf) {
		err = r.refuse("trailing_bytes")
		return
	}
	result = decoded.Value
	return
}
func (d *RecoverableAcceptanceDispatcher) WriteFrame(frame []byte) error {
	v, err := servicePayload(frame)
	if err != nil {
		return err
	}
	if v.Service != "abstraction.job/acceptance@1" {
		return DispatchError("unknown_service")
	}
	switch v.Method {
	case "GetHistoryWindow":
		return DispatchError("wrong_mode")
	case "Submit":
		return DispatchError("wrong_mode")
	case "Reconcile":
		return DispatchError("wrong_mode")
	case "CancelWork":
		return DispatchError("wrong_mode")
	default:
		return DispatchError("unknown_method")
	}
}
func (d *RecoverableAcceptanceDispatcher) ExchangeFrame(frame []byte) ([]byte, error) {
	v, err := servicePayload(frame)
	if err != nil {
		return nil, err
	}
	if v.Service != "abstraction.job/acceptance@1" {
		return serviceReply(v, "", DispatchError("unknown_service"))
	}
	switch v.Method {
	case "GetHistoryWindow":
		r := &reader{buf: []byte(v.Arguments), depth: 1}
		r.ws()
		args, err := r.decodeOARecoverableAcceptanceGetHistoryWindowArguments()
		if err != nil {
			return serviceReply(v, "", err)
		}
		r.ws()
		if r.pos != len(r.buf) {
			return serviceReply(v, "", r.refuse("trailing_bytes"))
		}
		payload, err := d.invokeGetHistoryWindow(args)
		return serviceReply(v, payload, err)
	case "Submit":
		r := &reader{buf: []byte(v.Arguments), depth: 1}
		r.ws()
		args, err := r.decodeOARecoverableAcceptanceSubmitArguments()
		if err != nil {
			return serviceReply(v, "", err)
		}
		r.ws()
		if r.pos != len(r.buf) {
			return serviceReply(v, "", r.refuse("trailing_bytes"))
		}
		payload, err := d.invokeSubmit(args)
		return serviceReply(v, payload, err)
	case "Reconcile":
		r := &reader{buf: []byte(v.Arguments), depth: 1}
		r.ws()
		args, err := r.decodeOARecoverableAcceptanceReconcileArguments()
		if err != nil {
			return serviceReply(v, "", err)
		}
		r.ws()
		if r.pos != len(r.buf) {
			return serviceReply(v, "", r.refuse("trailing_bytes"))
		}
		payload, err := d.invokeReconcile(args)
		return serviceReply(v, payload, err)
	case "CancelWork":
		r := &reader{buf: []byte(v.Arguments), depth: 1}
		r.ws()
		args, err := r.decodeOARecoverableAcceptanceCancelWorkArguments()
		if err != nil {
			return serviceReply(v, "", err)
		}
		r.ws()
		if r.pos != len(r.buf) {
			return serviceReply(v, "", r.refuse("trailing_bytes"))
		}
		payload, err := d.invokeCancelWork(args)
		return serviceReply(v, payload, err)
	default:
		return serviceReply(v, "", DispatchError("unknown_method"))
	}
}
func (d *RecoverableAcceptanceDispatcher) invokeGetHistoryWindow(args *OARecoverableAcceptanceGetHistoryWindowArguments) (payload Raw, err error) {
	defer func() {
		if p := recover(); p != nil {
			payload = ""
			if _, ok := p.(*Refusal); ok {
				err = &ServiceError{Code: "invalid_result"}
			} else {
				err = &ServiceError{Code: "handler_error", Message: "handler failed"}
			}
		}
	}()
	var result HistoryWindow
	result, err = d.Handler.GetHistoryWindow()
	if err != nil {
		return
	}
	value := OARecoverableAcceptanceGetHistoryWindowResult{Value: result}
	payload = Raw(encOARecoverableAcceptanceGetHistoryWindowResult(nil, &value, 1))
	r := &reader{buf: []byte(payload), depth: 1}
	r.ws()
	if _, e := r.decodeOARecoverableAcceptanceGetHistoryWindowResult(); e != nil {
		payload = ""
		err = &ServiceError{Code: "invalid_result"}
		return
	}
	r.ws()
	if r.pos != len(r.buf) {
		payload = ""
		err = &ServiceError{Code: "invalid_result"}
	}
	return
}
func (d *RecoverableAcceptanceDispatcher) invokeSubmit(args *OARecoverableAcceptanceSubmitArguments) (payload Raw, err error) {
	defer func() {
		if p := recover(); p != nil {
			payload = ""
			if _, ok := p.(*Refusal); ok {
				err = &ServiceError{Code: "invalid_result"}
			} else {
				err = &ServiceError{Code: "handler_error", Message: "handler failed"}
			}
		}
	}()
	var result AcceptanceResult
	result, err = d.Handler.Submit(args.Submission)
	if err != nil {
		return
	}
	value := OARecoverableAcceptanceSubmitResult{Value: result}
	payload = Raw(encOARecoverableAcceptanceSubmitResult(nil, &value, 1))
	r := &reader{buf: []byte(payload), depth: 1}
	r.ws()
	if _, e := r.decodeOARecoverableAcceptanceSubmitResult(); e != nil {
		payload = ""
		err = &ServiceError{Code: "invalid_result"}
		return
	}
	r.ws()
	if r.pos != len(r.buf) {
		payload = ""
		err = &ServiceError{Code: "invalid_result"}
	}
	return
}
func (d *RecoverableAcceptanceDispatcher) invokeReconcile(args *OARecoverableAcceptanceReconcileArguments) (payload Raw, err error) {
	defer func() {
		if p := recover(); p != nil {
			payload = ""
			if _, ok := p.(*Refusal); ok {
				err = &ServiceError{Code: "invalid_result"}
			} else {
				err = &ServiceError{Code: "handler_error", Message: "handler failed"}
			}
		}
	}()
	var result AcceptanceResult
	result, err = d.Handler.Reconcile(args.Identity)
	if err != nil {
		return
	}
	value := OARecoverableAcceptanceReconcileResult{Value: result}
	payload = Raw(encOARecoverableAcceptanceReconcileResult(nil, &value, 1))
	r := &reader{buf: []byte(payload), depth: 1}
	r.ws()
	if _, e := r.decodeOARecoverableAcceptanceReconcileResult(); e != nil {
		payload = ""
		err = &ServiceError{Code: "invalid_result"}
		return
	}
	r.ws()
	if r.pos != len(r.buf) {
		payload = ""
		err = &ServiceError{Code: "invalid_result"}
	}
	return
}
func (d *RecoverableAcceptanceDispatcher) invokeCancelWork(args *OARecoverableAcceptanceCancelWorkArguments) (payload Raw, err error) {
	defer func() {
		if p := recover(); p != nil {
			payload = ""
			if _, ok := p.(*Refusal); ok {
				err = &ServiceError{Code: "invalid_result"}
			} else {
				err = &ServiceError{Code: "handler_error", Message: "handler failed"}
			}
		}
	}()
	var result CancellationResult
	result, err = d.Handler.CancelWork(args.Identity)
	if err != nil {
		return
	}
	value := OARecoverableAcceptanceCancelWorkResult{Value: result}
	payload = Raw(encOARecoverableAcceptanceCancelWorkResult(nil, &value, 1))
	r := &reader{buf: []byte(payload), depth: 1}
	r.ws()
	if _, e := r.decodeOARecoverableAcceptanceCancelWorkResult(); e != nil {
		payload = ""
		err = &ServiceError{Code: "invalid_result"}
		return
	}
	r.ws()
	if r.pos != len(r.buf) {
		payload = ""
		err = &ServiceError{Code: "invalid_result"}
	}
	return
}
